{{- if index .Values "external-secrets-operator" "clusterSecretStore" "create" -}}
{{- if gt (len .Values.clustersConfig) 1 }}
{{- $root := . }}
{{- $stores := (include "tfy-agent.clustersConfig.uniqueSecretStores" . | fromJson).stores }}
{{- range $store := $stores }}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ index $store "clusterSecretStoreName" }}
  labels:
    {{- include "tfy-agent.commonLabels" $root | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    {{- include "tfy-agent.commonAnnotations" $root | nindent 4 }}
spec:
  {{- if not (has "*" (index $store "namespaces")) }}
  conditions:
    - namespaces:
        {{- range $namespace := index $store "namespaces" }}
        - {{ $namespace | quote }}
        {{- end }}
  {{- end }}
  provider:
    webhook:
      url: {{ printf "%s/api/svc/v1/control-plane/secret?secret_ref=%s" (index $store "controlPlaneURL") "{{ .remoteRef.key }}" | quote }}
      method: GET
      result:
        jsonPath: $.value
      headers:
        Authorization: {{ printf "Bearer {{ .auth.%s }}" (index $store "tokenSecretKey") | quote }}
      secrets:
        - name: auth
          secretRef:
            key: {{ index $store "tokenSecretKey" }}
            name: {{ include "tfy-agent.secretName" $root }}
            namespace: {{ $root.Release.Namespace }}
{{- end }}
{{- else }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ index .Values "external-secrets-operator" "clusterSecretStore" "name" }}
  labels:
    {{- include "tfy-agent.commonLabels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    {{- include "tfy-agent.commonAnnotations" . | nindent 4 }}
spec:
  provider:
    webhook:
      url: {{ include "tfy-agent.clusterSecretStore.webhookUrl" . | quote }}
      method: GET
      result:
        jsonPath: $.value
      headers:
        Authorization: {{ printf "Bearer %s" "{{ .auth.CLUSTER_TOKEN }}" | quote }}
      secrets:
        - name: auth
          secretRef:
            key: CLUSTER_TOKEN
            name: {{ include "tfy-agent.secretName" . }}
            namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
