{{- if index .Values "external-secrets-operator" "clusterSecretStore" "create" -}}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ index .Values "external-secrets-operator" "clusterSecretStore" "name" }}
  labels:
    {{- include "tfy-agent.commonLabels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    {{- include "tfy-agent.commonAnnotations" . | nindent 4 }}
spec:
  provider:
    webhook:
      url: {{ include "tfy-agent.clusterSecretStore.webhookUrl" . | quote }}
      method: GET
      result:
        jsonPath: $.value
      headers:
        Authorization: {{ printf "Bearer %s" "{{ .auth.CLUSTER_TOKEN }}" | quote }}
      secrets:
        - name: auth
          secretRef:
            key: CLUSTER_TOKEN
            name: {{ include "tfy-agent.secretName" . }}
            namespace: {{ .Release.Namespace }}
{{- end }}
