{{- $logicalClusters := .Values.config.logicalClusters | default list -}}
{{- if gt (len $logicalClusters) 0 }}
{{- $root := . -}}
{{- range $logicalClusters }}
{{- if and .clusterToken (not .clusterTokenSecret) }}
{{- $tokenSecretName := printf "%s-%s-token" (include "tfy-agent.fullname" $root | trunc 40 | trimSuffix "-") .name -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $tokenSecretName }}
  labels:
    external-secrets.io/type: webhook
    truefoundry.com/logical-cluster: {{ .name | quote }}
    {{- include "tfy-agent.commonLabels" $root | nindent 4 }}
  annotations:
    {{- include "tfy-agent.commonAnnotations" $root | nindent 4 }}
stringData:
  CLUSTER_TOKEN: {{ .clusterToken | quote }}
{{- end }}
{{- end }}
{{- end }}
