{{- if and .Values.mlfoundryServer.enabled .Values.mlfoundryServer.serviceMonitor.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mlfoundry-server.fullname" . }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "mlfoundry-server.serviceMonitorLabels" . | nindent 4 }}
  annotations:
    {{- include "mlfoundry-server.serviceMonitorAnnotations" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ include "global.namespace" . }}
  selector:
    matchLabels:
      {{- include "truefoundry.selectorLabels" (dict "context" . "name" "mlfoundry-server") | nindent 6 }}
  endpoints:
    - targetPort: {{ .Values.mlfoundryServer.service.port }}
      path: /metrics
      honorLabels: true
      interval: 10s
{{- end -}}
