apiVersion: v2
name: tfy-llm-gateway
version: 0.159.1
description: "Truefoundry LLM Gateway deployment chart"
maintainers:
  - name: truefoundry
dependencies:
  - name: redis
    version: 24.0.0
    condition: redis.enabled
  - name: tfy-sandbox-server
    repository: file://charts/tfy-sandbox-server
    version: 0.3.3
    condition: sandbox.devMode.enabled
