apiVersion: v2
name: tfy-llm-gateway
version: 0.173.0
description: "Truefoundry LLM Gateway deployment chart"
maintainers:
  - name: truefoundry
dependencies:
  - name: redis
    version: 24.0.0
    condition: redis.enabled
  - name: tfy-sandbox-server
    repository: oci://tfy.jfrog.io/tfy-helm
    version: 0.3.3
    condition: sandbox.devMode.enabled
