apiVersion: v2
name: tfy-llm-gateway
version: 0.154.0-rc.2
description: "Truefoundry LLM Gateway deployment chart"
maintainers:
  - name: truefoundry
dependencies:
  - name: redis
    version: 24.0.0
    condition: redis.enabled
  - name: tfy-sandbox-server
    version: 0.1.0
    condition: sandbox.devMode.enabled
