global:
  tenantName: ""
  controlPlaneURL: ""
  customCA:
    enabled: true
    existingConfigMap:
      name: tfy-llm-gateway-custom-ca
      overrideCAList: false
proxy:
  tls:
    enabled: true
    secretName: tfy-llm-gateway-proxy-tls

redis:
  enabled: true
