{{- if .Values.istio.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-11"
    helm.sh/resource-policy: {{ .Values.helm.resourcePolicy }}
  labels:
    truefoundry.com/infra-component: "istio-base"
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: tfy-apps
  source:
    chart: base
    repoURL: {{ if (.Values.global | default dict).repoURL }}{{ (.Values.global | default dict).repoURL }}/charts{{ else }}https://istio-release.storage.googleapis.com/charts{{ end }}
    targetRevision: 1.30.0
    helm:
      {{- if .Values.istio.base.valuesOverride }}
      values: |-
      {{ .Values.istio.base.valuesOverride | toYaml | nindent 8 }}
      {{- else }}
      values: ""
      {{- end }}
  syncPolicy:
    {{- toYaml .Values.istio.base.syncPolicy | nindent 4 }}
{{- end }}
