apiVersion: v2
name: tfy-netpol-operator
description: TrueFoundry annotation-driven NetworkPolicy operator
type: application
version: 0.2.2
appVersion: "0.6.0"
home: https://github.com/truefoundry/infra-charts
maintainers:
  - name: truefoundry
sources:
  - https://github.com/truefoundry/infra-charts/tree/main/charts/tfy-netpol-operator
  - https://github.com/truefoundry/network-policy-operator
keywords:
  - networkpolicy
  - operator
  - truefoundry
