{{- if and .Values.tfyInfraManager.enabled .Values.tfyInfraManager.serviceAccount.create .Values.tfyInfraManager.serviceAccount.name }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tfy-infra-manager.serviceAccountName" . }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "tfy-infra-manager.serviceAccountLabels" . | nindent 4 }}
  annotations:
    {{- include "tfy-infra-manager.serviceAccountAnnotations" . | nindent 4 }}
{{- if hasKey .Values.tfyInfraManager.serviceAccount "automountServiceAccountToken" }}
automountServiceAccountToken: {{ .Values.tfyInfraManager.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- end }}
