{{- include "tfy-llm-gateway.proxy.validate" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tfy-llm-gateway.fullname" . }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "tfy-llm-gateway.deploymentLabels" . | nindent 4 }}
  annotations:
    {{- include "tfy-llm-gateway.deploymentAnnotations" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ include "tfy-llm-gateway.replicas" . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tfy-llm-gateway.selectorLabels" . | nindent 6 }}
  strategy:
    {{- if .Values.rollout.enabled }}
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.rollout.maxSurge | default "100%" | quote }}
      maxUnavailable: {{ .Values.rollout.maxUnavailable | default 0 }}
    {{- end }}
  template:
    metadata:
      annotations:
        {{- include "tfy-llm-gateway.podAnnotations" . | nindent 8 }}
      labels:
        {{- include "tfy-llm-gateway.podLabels" . | nindent 8 }}
    spec:
      {{- if .Values.hostAliases }}
      hostAliases:
        {{- toYaml .Values.hostAliases | nindent 8 }}
      {{- end }}
      {{- if .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml .Values.dnsConfig | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tfy-llm-gateway.serviceAccountName" . }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext:
        {{- toYaml (omit .Values.podSecurityContext "enabled") | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds | default 30 }}
      {{- if or .Values.initContainers (and .Values.global.customCA.enabled (eq (include "tfy-llm-gateway.customCA.useDirectMount" .) "false")) }}
      initContainers:
        {{- if and .Values.global.customCA.enabled (eq (include "tfy-llm-gateway.customCA.useDirectMount" .) "false") }}
        {{- include "tfy-llm-gateway.customCA.initContainer" . | nindent 8 }}
        {{- end }}
        {{- if .Values.initContainers }}
        {{- toYaml .Values.initContainers | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.securityContext.enabled }}
          securityContext:
            {{- toYaml (omit .Values.securityContext "enabled") | nindent 12 }}
          {{- end }}
          env:
            {{- include "tfy-llm-gateway.env" . | trim | nindent 12 }}
          image: "{{ .Values.image.registry | default .Values.global.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- include "tfy-llm-gateway.resources" . | nindent 12 }}
          {{- if .Values.healthcheck.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthcheck.liveness.path }}
              port: {{ .Values.healthcheck.liveness.port }}
            initialDelaySeconds: {{ .Values.healthcheck.liveness.initialDelaySeconds | default 10 }}
            periodSeconds: {{ .Values.healthcheck.liveness.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.healthcheck.liveness.timeoutSeconds | default 5 }}
            successThreshold: {{ .Values.healthcheck.liveness.successThreshold | default 1 }}
            failureThreshold: {{ .Values.healthcheck.liveness.failureThreshold | default 3 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthcheck.readiness.path }}
              port: {{ .Values.healthcheck.readiness.port }}
            initialDelaySeconds: {{ .Values.healthcheck.readiness.initialDelaySeconds | default 10 }}
            periodSeconds: {{ .Values.healthcheck.readiness.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.healthcheck.readiness.timeoutSeconds | default 5 }}
            successThreshold: {{ .Values.healthcheck.readiness.successThreshold | default 1 }}
            failureThreshold: {{ .Values.healthcheck.readiness.failureThreshold | default 3 }}
          {{- end }}
          volumeMounts:
          - name: tmp-dir
            mountPath: /tmp
          {{- if gt (len .Values.extraVolumeMounts) 0 }}
          {{- toYaml .Values.extraVolumeMounts | nindent 10 }}
          {{- end }}
          {{- if .Values.oidc.enabled }}
          - name: oidc-config
            mountPath: /etc/oidc
            readOnly: true
          {{- end }}
          {{- if .Values.global.customCA.enabled }}
          {{- include "tfy-llm-gateway.customCA.volumeMounts" . | nindent 10 }}
          {{- end }}
        {{- if .Values.proxy.tls.enabled }}
        - name: {{ .Values.proxy.name }}
          {{- if .Values.proxy.securityContext.enabled }}
          securityContext:
            {{- toYaml (omit .Values.proxy.securityContext "enabled") | nindent 12 }}
          {{- end }}
          image: "{{ .Values.proxy.image.registry | default .Values.image.registry | default .Values.global.image.registry }}/{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag | default .Values.image.tag }}"
          imagePullPolicy: {{ .Values.proxy.imagePullPolicy | default .Values.imagePullPolicy }}
          ports:
            - name: https
              containerPort: {{ .Values.proxy.containerPort }}
              protocol: TCP
          volumeMounts:
            {{- include "tfy-llm-gateway.proxy.volumeMounts" . | nindent 12 }}
          resources:
            {{- toYaml .Values.proxy.resources | nindent 12 }}
          {{- if .Values.proxy.healthcheck.enabled }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.proxy.healthcheck.readiness.port | default .Values.proxy.containerPort }}
            initialDelaySeconds: {{ .Values.proxy.healthcheck.readiness.initialDelaySeconds | default 5 }}
            periodSeconds: {{ .Values.proxy.healthcheck.readiness.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.proxy.healthcheck.readiness.timeoutSeconds | default 1 }}
            successThreshold: {{ .Values.proxy.healthcheck.readiness.successThreshold | default 1 }}
            failureThreshold: {{ .Values.proxy.healthcheck.readiness.failureThreshold | default 3 }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.proxy.healthcheck.liveness.port | default .Values.proxy.containerPort }}
            initialDelaySeconds: {{ .Values.proxy.healthcheck.liveness.initialDelaySeconds | default 15 }}
            periodSeconds: {{ .Values.proxy.healthcheck.liveness.periodSeconds | default 20 }}
            timeoutSeconds: {{ .Values.proxy.healthcheck.liveness.timeoutSeconds | default 1 }}
            successThreshold: {{ .Values.proxy.healthcheck.liveness.successThreshold | default 1 }}
            failureThreshold: {{ .Values.proxy.healthcheck.liveness.failureThreshold | default 3 }}
          {{- end }}
        {{- end }}
      imagePullSecrets:
        {{- include "tfy-llm-gateway.imagePullSecrets" . | nindent 8 }}
      volumes:
      - name: tmp-dir
        emptyDir:
          sizeLimit: {{ include "tfy-llm-gateway.ephemeralStorage.limit" . }}
      {{- if gt (len .Values.extraVolumes) 0 }}
      {{- toYaml .Values.extraVolumes | nindent 6 }}
      {{- end }}
      {{- if .Values.oidc.enabled }}
      - name: oidc-config
        configMap:
          name: {{ include "tfy-llm-gateway.fullname" . }}-oidc-cm
      {{- end }}
      {{- if .Values.global.customCA.enabled }}
      {{- include "tfy-llm-gateway.customCA.volumes" . | nindent 6 }}
      {{- end }}
      {{- if .Values.proxy.tls.enabled }}
      {{- include "tfy-llm-gateway.proxy.volumes" . | nindent 6 }}
      {{- end }}
      nodeSelector:
        {{- include "tfy-llm-gateway.nodeSelector" . | nindent 8 }}
      affinity:
        {{- include "tfy-llm-gateway.affinity" . | nindent 8 }}
      topologySpreadConstraints:
        {{- if .Values.topologySpreadConstraints }}
        {{- toYaml .Values.topologySpreadConstraints | nindent 8 }}
        {{- else }}
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              {{- include "tfy-llm-gateway.selectorLabels" . | nindent 14 }}
        {{- end }}
      tolerations:
        {{- include "tfy-llm-gateway.tolerations" . | nindent 8 }}