global:
  tenantName: ""
  controlPlaneURL: ""
  truefoundryImagePullConfigJSON: ""
  database:
    host: ""
    name: ""
    username: ""
    password: ""
  tfyApiKey: ""

tags:
  tracing: true
  llmGateway: true
  llmGatewayRequestLogging: true

devMode:
  enabled: true

truefoundryBootstrap:
  enabled: true

s3proxy:
  enabled: true

sparkHistoryServer:
  enabled: true

tfyWorkflowAdmin:
  enabled: true

truefoundryFrontendApp:
  enabled: false