{{/*
Expand the name of the chart.
*/}}
{{- define "truefoundry-monitoring.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
*/}}
{{- define "truefoundry-monitoring.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "truefoundry-monitoring.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "truefoundry-monitoring.labels" -}}
helm.sh/chart: {{ include "truefoundry-monitoring.chart" . }}
{{ include "truefoundry-monitoring.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "truefoundry-monitoring.selectorLabels" -}}
app.kubernetes.io/name: {{ include "truefoundry-monitoring.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Control plane namespace
*/}}
{{- define "truefoundry-monitoring.controlPlaneNamespace" -}}
{{- default "truefoundry" .Values.global.controlPlaneNamespace }}
{{- end }}

{{/*
Grafana datasource sidecar labels (common labels + discovery label).
*/}}
{{- define "truefoundry-monitoring.grafana.datasourceLabels" -}}
{{ include "truefoundry-monitoring.labels" . }}
{{ .Values.grafana.sidecar.datasources.label }}: {{ .Values.grafana.sidecar.datasources.labelValue | quote }}
{{- end -}}

{{/*
Grafana dashboard sidecar labels (common labels + discovery label).
*/}}
{{- define "truefoundry-monitoring.grafana.dashboardLabels" -}}
{{ include "truefoundry-monitoring.labels" . }}
{{ .Values.grafana.sidecar.dashboards.label }}: {{ .Values.grafana.sidecar.dashboards.labelValue | quote }}
{{- end -}}

{{/*
Replicate the kube-prometheus-stack fullname (26-char truncation) for the
"prometheus" subchart alias so the parent chart can reference subchart service
names without hard-coding a truncation artifact.
Requires prometheus.nameOverride="prometheus" in values.yaml so that the
subchart's $name matches the default used here (Helm aliases do NOT change
.Chart.Name inside the subchart).
See: kube-prometheus-stack/templates/_helpers.tpl  "kube-prometheus-stack.fullname"
*/}}
{{- define "truefoundry-monitoring.prometheus.fullname" -}}
{{- if .Values.prometheus.fullnameOverride -}}
{{- .Values.prometheus.fullnameOverride | trunc 26 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default "prometheus" .Values.prometheus.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 26 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 26 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{/*
Prometheus service name as generated by kube-prometheus-stack.
The service template always appends "-prometheus" to the chart fullname,
regardless of cleanPrometheusOperatorObjectNames.
*/}}
{{- define "truefoundry-monitoring.prometheus.serviceName" -}}
{{- printf "%s-prometheus" (include "truefoundry-monitoring.prometheus.fullname" .) -}}
{{- end -}}

{{/*
VictoriaLogs server service name.
The victoria-logs-single chart (nested inside tfy-logs) uses the standard Helm
fullname (<release>-victoria-logs-single) with a "-server" suffix for its service.
*/}}
{{- define "truefoundry-monitoring.logs.serviceName" -}}
{{- printf "%s-victoria-logs-single-server" .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
