{{- $tc := .Values.tfyConfigs | default dict -}}
{{- if $tc.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-default-policies-cm
  namespace: {{ include "global.namespace" . }}
data:
  default-policies.yaml: |-
    {{- if not $tc.configs.defaultPoliciesOverride }}
    {{ .Files.Get "files/tfy-configs/default-policies.yaml" | nindent 4 }}
    {{- else }}
    {{ toYaml $tc.configs.defaultPoliciesOverride | nindent 4 }}
    {{- end }}
{{- end }}
