{{- $tfyProxyServiceName := index (splitList "." (tpl (.Values.global.proxy.tfyProxyHost) .)) 0 -}}
{{- $tfyWorkflowAdminServiceName := index (splitList "." (tpl (.Values.global.proxy.tfyWorkflowAdminHost) .)) 0 -}}
{{- if and .Values.global.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "truefoundry.ingress.fullname" . }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "truefoundry.ingress.labels" . | nindent 4 }}
  annotations:
    {{- include "truefoundry.ingress.annotations" . | nindent 4 }}
spec:
  ingressClassName: {{ tpl .Values.global.ingress.ingressClassName $ }}
  {{- if .Values.global.ingress.tls }}
  tls:
    {{- tpl (.Values.global.ingress.tls | toYaml) $ | nindent 4 }}
  {{- end }}
  rules:
    {{- range $host := .Values.global.ingress.hosts }}
    - host: {{ tpl $host $ }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $tfyProxyServiceName }}
                port:
                  number: {{ $.Values.tfyProxy.service.port }}
          {{- if $.Values.tfyWorkflowAdmin.enabled }}
          - path: /flyteidl.service.AdminService/
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $tfyWorkflowAdminServiceName }}
                port:
                  number: {{ $.Values.tfyWorkflowAdmin.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
