apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cicd-templates-cm
  namespace: {{ include "global.namespace" . }}
data:
{{- if .Values.configs.cicdTemplates }}
  {{- range $key, $value := .Values.configs.cicdTemplates }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
{{- else }}
{{ (.Files.Glob "files/cicd-templates/*.yaml").AsConfig | indent 2 }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-chat
  namespace: {{ include "global.namespace" . }}
data:
{{- if .Values.configs.chat }}
  {{- range $key, $value := .Values.configs.chat }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
{{- else }}
{{ (.Files.Glob "files/chat/*.yaml").AsConfig | indent 2 }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-embedding
  namespace: {{ include "global.namespace" . }}
data:
{{- if .Values.configs.embedding }}
  {{- range $key, $value := .Values.configs.embedding }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
{{- else }}
{{ (.Files.Glob "files/embedding/*.yaml").AsConfig | indent 2 }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-image
  namespace: {{ include "global.namespace" . }}
data:
{{- if .Values.configs.image }}
  {{- range $key, $value := .Values.configs.image }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
{{- else }}
{{ (.Files.Glob "files/image/*.yaml").AsConfig | indent 2 }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-realtime
  namespace: {{ include "global.namespace" . }}
data:
{{- if .Values.configs.realtime }}
  {{- range $key, $value := .Values.configs.realtime }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
{{- else }}
{{ (.Files.Glob "files/realtime/*.yaml").AsConfig | indent 2 }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-rerank
  namespace: {{ include "global.namespace" . }}
data:
{{- if .Values.configs.rerank }}
  {{- range $key, $value := .Values.configs.rerank }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
{{- else }}
{{ (.Files.Glob "files/rerank/*.yaml").AsConfig | indent 2 }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-speech
  namespace: {{ include "global.namespace" . }}
data:
{{- if .Values.configs.speech }}
  {{- range $key, $value := .Values.configs.speech }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
{{- else }}
{{ (.Files.Glob "files/speech/*.yaml").AsConfig | indent 2 }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-transcription
  namespace: {{ include "global.namespace" . }}
data:
{{- if .Values.configs.transcription }}
  {{- range $key, $value := .Values.configs.transcription }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
{{- else }}
{{ (.Files.Glob "files/transcription/*.yaml").AsConfig | indent 2 }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-translation
  namespace: {{ include "global.namespace" . }}
data:
{{- if .Values.configs.translation }}
  {{- range $key, $value := .Values.configs.translation }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
{{- else }}
{{ (.Files.Glob "files/translation/*.yaml").AsConfig | indent 2 }}
{{- end }}