apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-chat-codesnippet-cm
  namespace: {{ include "global.namespace" . }}
data:
{{- if .Values.configs.codeSnippet.chat }}
  {{- range $key, $value := .Values.configs.codeSnippet.chat }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
{{- else }}
{{ (.Files.Glob "files/codesnippet/chat/*.ejs").AsConfig | indent 2 }}
{{- end }}


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-embedding-codesnippet-cm
  namespace: {{ include "global.namespace" . }}
data:
{{- if .Values.configs.codeSnippet.embedding }}
  {{- range $key, $value := .Values.configs.codeSnippet.embedding }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
{{- else }}
{{ (.Files.Glob "files/codesnippet/embedding/*.ejs").AsConfig | indent 2 }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-image-codesnippet-cm
  namespace: {{ include "global.namespace" . }}
data:
{{- if .Values.configs.codeSnippet.image }}
  {{- range $key, $value := .Values.configs.codeSnippet.image }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
{{- else }}
{{ (.Files.Glob "files/codesnippet/image/*.ejs").AsConfig | indent 2 }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-realtime-codesnippet-cm
  namespace: {{ include "global.namespace" . }}
data:
{{- if .Values.configs.codeSnippet.realtime }}
  {{- range $key, $value := .Values.configs.codeSnippet.realtime }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
{{- else }}
{{ (.Files.Glob "files/codesnippet/realtime/*.ejs").AsConfig | indent 2 }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-rerank-codesnippet-cm
  namespace: {{ include "global.namespace" . }}
data:
{{- if .Values.configs.codeSnippet.rerank }}
  {{- range $key, $value := .Values.configs.codeSnippet.rerank }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
{{- else }}
{{ (.Files.Glob "files/codesnippet/rerank/*.ejs").AsConfig | indent 2 }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-speech-codesnippet-cm
  namespace: {{ include "global.namespace" . }}
data:
{{- if .Values.configs.codeSnippet.speech }}
  {{- range $key, $value := .Values.configs.codeSnippet.speech }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
{{- else }}
{{ (.Files.Glob "files/codesnippet/speech/*.ejs").AsConfig | indent 2 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-transcription-codesnippet-cm
  namespace: {{ include "global.namespace" . }}
data:
{{- if .Values.configs.codeSnippet.transcription }}
  {{- range $key, $value := .Values.configs.codeSnippet.transcription }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
{{- else }}
{{ (.Files.Glob "files/codesnippet/transcription/*.ejs").AsConfig | indent 2 }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-translation-codesnippet-cm
  namespace: {{ include "global.namespace" . }}
data:
{{- if .Values.configs.codeSnippet.translation }}
  {{- range $key, $value := .Values.configs.codeSnippet.translation }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
{{- else }}
{{ (.Files.Glob "files/codesnippet/translation/*.ejs").AsConfig | indent 2 }}
{{- end }}
