{
 "title": "Cluster - Nodes",
 "tags": [
  "truefoundry",
  "kubernetes"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance_type",
    "label": "Instance Type",
    "query": {
     "query": "label_values(kube_node_labels,instance_type)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_node_labels{instance_type=~\"$instance_type\"},node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count by (node) (kube_node_labels{job=\"kube-state-metrics\",instance_type=~\"$instance_type\",node=~\"$node\"}))",
     "legendFormat": "Number of Nodes"
    }
   ]
  },
  {
   "title": "Number of Nodes by capacity type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (capacity_type) ((count by (node, capacity_type) (kube_node_labels{job=\"kube-state-metrics\",instance_type=~\"$instance_type\",node=~\"$node\"})))",
     "legendFormat": "{{capacity_type}}"
    }
   ]
  },
  {
   "title": "Node Uptime",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ceil((clamp_max(max_over_time(max by (node) ((node_time_seconds{job=\"node-exporter\"} >= ${__from:date:seconds}) - node_boot_time_seconds{job=\"node-exporter\"})[$__range:]), ${__to:date:seconds} - ${__from:date:seconds}) / 60) * on (node) group_left (instance_type, capacity_type) max_over_time (max by (node, instance_type, capacity_type) (kube_node_labels{job=\"kube-state-metrics\",instance_type=~\"$instance_type\",node=~\"$node\"})[$__range:]))"
    }
   ]
  },
  {
   "title": "Node Total Uptime Total (Minutes)",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "ceil(sum by (instance_type,capacity_type) (\n(\nclamp_max(max_over_time(node_time_seconds{job=\"node-exporter\"}[$__interval:]), time()) \n-\nclamp_min(\n  min_over_time(node_boot_time_seconds{job=\"node-exporter\"}[$__interval:])\n  , time() - $__interval_ms / 1000 * 1\n  )\n) \n* on (node) group_left (instance_type, capacity_type) (max_over_time(max by (node, instance_type, capacity_type) (kube_node_labels{job=\"kube-state-metrics\",instance_type=~\"$instance_type\",node=~\"$node\"})[$__interval:])) ) / 60)"
    }
   ]
  },
  {
   "title": "Node Pressure Conditions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (condition, node) (kube_node_status_condition{status=\"true\", condition!=\"Ready\"}) * on (node) group_left (instance_type, capacity_type) (max_over_time(max by (node, instance_type, capacity_type) (kube_node_labels{job=\"kube-state-metrics\",instance_type=~\"$instance_type\",node=~\"$node\"})[$__interval:])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unschedulable Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max_over_time(max by (node) (kube_node_spec_unschedulable)[$__interval:]) * on (node) group_left (instance_type, capacity_type) (max_over_time(max by (node, instance_type, capacity_type) (kube_node_labels{job=\"kube-state-metrics\",instance_type=~\"$instance_type\",node=~\"$node\"})[$__interval:])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (node, instance_type) (max_over_time((instance:node_cpu_utilisation:rate5m[$__interval])) * 100.0 * on (node) group_left (instance_type, capacity_type) max by (node, instance_type, capacity_type) (kube_node_labels{job=\"kube-state-metrics\", instance_type=~\"$instance_type\",node=~\"$node\"}))"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (node, instance_type) (max_over_time(instance:node_memory_utilisation:ratio[$__interval]) * 100 * on (node) group_left (instance_type, capacity_type) max by (node, instance_type, capacity_type) (kube_node_labels{job=\"kube-state-metrics\",instance_type=~\"$instance_type\",node=~\"$node\"}))"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (node, instance_type) (((1 - sum by (node) (node_filesystem_avail_bytes{device!=\"rootfs\", job=\"node-exporter\"}) / sum by (node)( node_filesystem_size_bytes{device!=\"rootfs\",job=\"node-exporter\"})) * 100) * on (node) group_left (instance_type, capacity_type) max by (node, instance_type, capacity_type) (kube_node_labels{job=\"kube-state-metrics\",job=\"kube-state-metrics\",instance_type=~\"$instance_type\",node=~\"$node\"}))"
    }
   ]
  }
 ]
}