{
 "title": "TrueFoundry Control Plane",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "deployments",
    "query": {
     "query": "label_values(kube_deployment_spec_replicas{namespace=\"truefoundry\"},deployment)"
    }
   },
   {
    "name": "statefulsets",
    "query": {
     "query": "label_values(kube_statefulset_replicas{namespace=\"truefoundry\"},statefulset)"
    }
   },
   { "name": "namespace", "query": "${VAR_NAMESPACE}" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(label_replace(((sum(rate(container_cpu_usage_seconds_total{image!=\"\",pod=~\"$deployments-.*\",namespace=\"$namespace\",job=\"kubelet\"}[2m])) by (pod) / max(kube_pod_container_resource_requests{resource=\"cpu\",job=\"kube-state-metrics\",namespace=\"$namespace\"}) by (pod)) * on(pod) group_left(owner_name) (sum without (instance) (kube_pod_owner{owner_kind=\"ReplicaSet\",job=\"kube-state-metrics\",namespace=\"$namespace\"}))),\"replicaset\", \"$1\", \"owner_name\", \"(.*)\") * on(replicaset) group_left(owner_name) (sum without (instance) (kube_replicaset_owner{job=\"kube-state-metrics\",namespace=\"$namespace\"})) OR (sum(rate(container_cpu_usage_seconds_total{image!=\"\",pod=~\"$statefulsets-.*\",namespace=\"$namespace\",job=\"kubelet\"}[2m])) by (pod) / max(kube_pod_container_resource_requests{resource=\"cpu\",job=\"kube-state-metrics\",namespace=\"$namespace\"}) by (pod)) * on(pod) group_left(owner_name) (sum without (instance) (kube_pod_owner{owner_kind=\"StatefulSet\",job=\"kube-state-metrics\",namespace=\"$namespace\"}))) by (owner_name) * 100",
     "legendFormat": "{{owner_name}}"
    },
    {
     "expr": "max(label_replace(((sum(container_memory_usage_bytes{image!=\"\",pod=~\"$deployments-.*\",namespace=\"$namespace\",job=\"kubelet\"}) by (pod) / max(kube_pod_container_resource_requests{resource=\"memory\",job=\"kube-state-metrics\",namespace=\"$namespace\"}) by (pod)) * on(pod) group_left(owner_name) (sum without (instance) (kube_pod_owner{owner_kind=\"ReplicaSet\",job=\"kube-state-metrics\",namespace=\"$namespace\"}))),\"replicaset\", \"$1\", \"owner_name\", \"(.*)\") * on(replicaset) group_left(owner_name) (sum without (instance) (kube_replicaset_owner{job=\"kube-state-metrics\",namespace=\"$namespace\"})) OR (sum(container_memory_usage_bytes{image!=\"\",pod=~\"$statefulsets-.*\",namespace=\"$namespace\",job=\"kubelet\",namespace=\"$namespace\"}) by (pod) / max(kube_pod_container_resource_requests{resource=\"memory\",job=\"kube-state-metrics\",namespace=\"$namespace\"}) by (pod)) * on(pod) group_left(owner_name) (sum without (instance) (kube_pod_owner{owner_kind=\"StatefulSet\",job=\"kube-state-metrics\",namespace=\"$namespace\"}))) by (owner_name) * 100",
     "legendFormat": "{{owner_name}}"
    },
    {
     "expr": "max(label_replace((sum(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*$statefulsets-.*\",namespace=\"$namespace\",job=\"kubelet\"}) by (persistentvolumeclaim) / max(kubelet_volume_stats_capacity_bytes{job=\"kubelet\",namespace=\"$namespace\"}) by (persistentvolumeclaim)), \"owner_name\", \n      \"$1\", \n      \"persistentvolumeclaim\", \n      \".*$statefulsets.*\")) by (owner_name) * 100"
    },
    {
     "expr": "max(label_replace(((sum(changes(kube_pod_status_ready{condition=\"true\",pod=~\"$deployments-.*\",namespace=\"$namespace\",job=\"kube-state-metrics\"}[15m])) by (pod)) * on(pod) group_left(owner_name) (sum without (instance) (kube_pod_owner{owner_kind=\"ReplicaSet\",job=\"kube-state-metrics\",namespace=\"$namespace\"}))),\"replicaset\", \"$1\", \"owner_name\", \"(.*)\") * on(replicaset) group_left(owner_name) (sum without (instance) (kube_replicaset_owner{job=\"kube-state-metrics\",namespace=\"$namespace\"})) OR (sum(changes(kube_pod_status_ready{condition=\"true\",pod=~\"$statefulsets-.*\",namespace=\"$namespace\",job=\"kube-state-metrics\"}[15m])) by (pod)) * on(pod) group_left(owner_name) (sum without (instance) (kube_pod_owner{owner_kind=\"StatefulSet\",job=\"kube-state-metrics\",namespace=\"$namespace\"}))) by (owner_name)",
     "legendFormat": "{{owner_name}}"
    },
    {
     "expr": "max(label_replace(((sum(kube_pod_status_phase{phase!=\"Running\",pod=~\"$deployments-.*\",namespace=\"$namespace\",job=\"kube-state-metrics\"}) by (pod)) * on(pod) group_left(owner_name) (sum without (instance) (kube_pod_owner{owner_kind=\"ReplicaSet\",job=\"kube-state-metrics\",namespace=\"$namespace\"}))),\"replicaset\", \"$1\", \"owner_name\", \"(.*)\") * on(replicaset) group_left(owner_name) (sum without (instance) (kube_replicaset_owner{job=\"kube-state-metrics\",namespace=\"$namespace\"})) OR (sum(kube_pod_status_phase{phase!=\"Running\",pod=~\"$statefulsets-.*\",namespace=\"$namespace\",job=\"kube-state-metrics\"}) by (pod)) * on(pod) group_left(owner_name) (sum without (instance) (kube_pod_owner{owner_kind=\"StatefulSet\",job=\"kube-state-metrics\",namespace=\"$namespace\"}))) by (owner_name)"
    }
   ]
  },
  { "title": "NATS metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Message size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "max(nats_stream_total_bytes) by (stream_name)",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  {
   "title": "Message counts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "max(nats_stream_total_messages) by (stream_name)",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  {
   "title": "Message per sec",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "expr": "max(rate(nats_stream_total_messages[$__rate_interval])) by (stream_name)",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  {
   "title": "Message rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(nats_varz_in_msgs[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(nats_varz_out_msgs[$__rate_interval]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Server CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 27 },
   "targets": [
    { "expr": "nats_varz_cpu", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Server memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 27 },
   "targets": [
    { "expr": "nats_varz_mem/1024/1024", "legendFormat": "{{pod}}" }
   ]
  },
  { "title": "Deployment: $deployments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }, "repeat": "deployments" },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "max(sum(rate(container_cpu_usage_seconds_total{image!=\"\",pod=~\"$deployments-.*\",namespace=\"$namespace\",job=\"kubelet\"}[$__rate_interval])) by (pod))",
     "legendFormat": "Usage"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{resource=\"cpu\",pod=~\"$deployments-.*\",namespace=\"$namespace\",job=\"kube-state-metrics\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{resource=\"cpu\",pod=~\"$deployments-.*\",namespace=\"$namespace\",job=\"kube-state-metrics\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "expr": "max(sum(container_memory_usage_bytes{image!=\"\",pod=~\"$deployments-.*\",namespace=\"$namespace\",job=\"kubelet\"}) by (pod))/1024/1024",
     "legendFormat": "Used"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{resource=\"memory\",pod=~\"$deployments-.*\",namespace=\"$namespace\",job=\"kube-state-metrics\"})/1024/1024",
     "legendFormat": "Requested"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{resource=\"memory\",pod=~\"$deployments-.*\",namespace=\"$namespace\",job=\"kube-state-metrics\"})/1024/1024",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
   "targets": [
    {
     "expr": "round((sum(rate(container_network_receive_bytes_total{pod=~\"$deployments-.*\",namespace=\"$namespace\",job=\"kubelet\"}[$__rate_interval])))/1000000, 0.001)",
     "legendFormat": "Reveived"
    },
    {
     "expr": "round((sum(rate(container_network_transmit_bytes_total{pod=~\"$deployments-.*\",namespace=\"$namespace\",job=\"kubelet\"}[$__rate_interval])))/1000000, 0.001)",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Pods phase",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum by (phase) (kube_pod_status_phase{pod=~\"$deployments-.*\",job=\"kube-state-metrics\",namespace=\"$namespace\"})",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 39 },
   "targets": [
    {
     "expr": "round((sum(rate(container_fs_reads_bytes_total{pod=~\"$deployments-.*\",container=~\".*\",namespace=\"$namespace\",job=\"kubelet\"}[$__rate_interval])))/1000000, 0.001)",
     "legendFormat": "Read"
    },
    {
     "expr": "round((sum(rate(container_fs_writes_bytes_total{pod=~\"$deployments-.*\",container=~\".*\",namespace=\"$namespace\",job=\"kubelet\"}[$__rate_interval])))/1000000, 0.001)",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Pod restarts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 39 },
   "targets": [
    {
     "expr": "max(floor(increase(kube_pod_container_status_restarts_total{pod=~\"$deployments-.*\",namespace=\"$namespace\",job=\"kube-state-metrics\"}[$__rate_interval]))) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "StatefulSets: $statefulsets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 422 }, "repeat": "statefulsets" },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 423 },
   "targets": [
    {
     "expr": "max(sum(rate(container_cpu_usage_seconds_total{image!=\"\",pod=~\"$statefulsets-.*\",namespace=\"$namespace\",job=\"kubelet\"}[$__rate_interval])) by (pod))",
     "legendFormat": "Usage"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{resource=\"cpu\",pod=~\"$statefulsets-.*\",job=\"kube-state-metrics\",namespace=\"$namespace\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{resource=\"cpu\",pod=~\"$statefulsets-.*\",namespace=\"$namespace\",job=\"kube-state-metrics\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 423 },
   "targets": [
    {
     "expr": "max(sum(container_memory_usage_bytes{image!=\"\",pod=~\"$statefulsets-.*\",namespace=\"$namespace\",job=\"kubelet\"}) by (pod))/1024/1024",
     "legendFormat": "Used"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{resource=\"memory\",pod=~\"$statefulsets-.*\",namespace=\"$namespace\",job=\"kube-state-metrics\"})/1024/1024",
     "legendFormat": "Requested"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{resource=\"memory\",pod=~\"$statefulsets-.*\",namespace=\"$namespace\",job=\"kube-state-metrics\"})/1024/1024",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 423 },
   "targets": [
    {
     "expr": "round((sum(rate(container_network_receive_bytes_total{pod=~\"$statefulsets-.*\",namespace=\"$namespace\",job=\"kubelet\"}[$__rate_interval])))/1000000, 0.001)",
     "legendFormat": "Reveived"
    },
    {
     "expr": "round((sum(rate(container_network_transmit_bytes_total{pod=~\"$statefulsets-.*\",job=\"kubelet\",namespace=\"$namespace\"}[$__rate_interval])))/1000000, 0.001)",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Pods phase",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 428 },
   "targets": [
    {
     "expr": "sum by (phase) (kube_pod_status_phase{pod=~\"$statefulsets-.*\",job=\"kube-state-metrics\",namespace=\"$namespace\",job=\"kube-state-metrics\"})",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 428 },
   "targets": [
    {
     "expr": "round((sum(rate(container_fs_reads_bytes_total{pod=~\"$statefulsets-.*\",container=~\".*\",namespace=\"$namespace\",job=\"kubelet\"}[$__rate_interval])))/1000000, 0.001)",
     "legendFormat": "Read"
    },
    {
     "expr": "round((sum(rate(container_fs_writes_bytes_total{pod=~\"$statefulsets-.*\",container=~\".*\",namespace=\"$namespace\",job=\"kubelet\"}[$__rate_interval])))/1000000, 0.001)",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Pod restarts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 428 },
   "targets": [
    {
     "expr": "max(floor(increase(kube_pod_container_status_restarts_total{pod=~\"$statefulsets-.*\",namespace=\"$namespace\",job=\"kube-state-metrics\"}[$__rate_interval]))) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}