{
 "title": "Control Plane View",
 "description": "Logs collected from Kubernetes, stored in Loki",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "query", "label": "Search Query" },
   { "name": "namespace", "query": "label_values(namespace)" },
   { "name": "path", "label": "path", "query": { "query": "label_values(path)" } },
   { "name": "container", "query": "label_values(container)" },
   { "name": "method", "label": "method", "query": { "query": "label_values(method)" } },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(nats_server_total_streams, server_id)"
    }
   },
   {
    "name": "nats_stream",
    "label": "NATS stream",
    "query": {
     "query": "label_values(nats_stream_last_seq, stream_name)"
    }
   },
   {
    "name": "consumer",
    "label": "Consumer",
    "query": {
     "query": "label_values(nats_consumer_num_pending,consumer_name)"
    }
   },
   { "name": "stream", "label": "stream", "query": { "query": "label_values(stream)" } }
  ]
 },
 "panels": [
  {
   "title": "LLM Gateway Clickhouse",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "round(\n  sum by (pod) (\n    container_memory_working_set_bytes{\n      namespace=\"truefoundry\",\n      container!=\"POD\",\n      container!=\"\",\n      pod!=\"\",\n      pod=~\".*-tfy-llm-gateway-infra-clickhouse.*\"\n    }\n  ) / 1000000, \n  0.001\n)\n",
       "legendFormat": "Used {{pod}}"
      },
      {
       "expr": "round(\n  sum by (pod) (\n    kube_pod_container_resource_requests{\n      job=\"kube-state-metrics\",\n      resource=\"memory\",\n      namespace=\"truefoundry\",\n      pod=~\".*-tfy-llm-gateway-infra-clickhouse.*\"\n    }\n  ) / 1000000, \n  0.001\n)\n",
       "legendFormat": "Requested {{pod}}"
      },
      {
       "expr": "sum by (pod) (\n  kube_pod_container_resource_limits{\n    job=\"kube-state-metrics\",\n    resource=\"memory\",\n    namespace=\"truefoundry\",\n    pod=~\".*-tfy-llm-gateway-infra-clickhouse.*\"\n  }\n) / 1000000\n",
       "legendFormat": "Limits {{pod}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "round(\n  sum by (pod) (\n    rate(container_cpu_usage_seconds_total{\n      namespace=\"truefoundry\",\n      container!=\"POD\",\n      container!=\"\",\n      pod=~\".*-tfy-llm-gateway-infra-clickhouse.*\",\n    }[$__rate_interval])\n  ), \n  0.001\n)\n",
       "legendFormat": "Used {{pod}}"
      },
      {
       "expr": "round(\n  sum by (pod) (\n    kube_pod_container_resource_limits{\n      job=\"kube-state-metrics\",\n      resource=\"cpu\",\n      namespace=\"truefoundry\",\n      pod=~\".*-tfy-llm-gateway-infra-clickhouse.*\"\n    }\n  ), \n  0.001\n)\n",
       "legendFormat": "Requested {{pod}}"
      },
      {
       "expr": "round(\n  sum by (pod) (\n    kube_pod_container_resource_limits{\n      job=\"kube-state-metrics\",\n      resource=\"cpu\",\n      namespace=\"truefoundry\",\n      pod=~\".*-tfy-llm-gateway-infra-clickhouse.*\"\n    }\n  ), \n  0.001\n)\n",
       "legendFormat": "Limits {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Servicefoundry Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failed API requests information",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(http_request_duration_seconds_count{status_code=~\"^5..$\", container=~\"servicefoundry-server.*\", path=~\"$path\", method=~\"$method\", namespace=\"truefoundry\"}) by (method, path, status_code)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests taking more than 300MS P95 in the last 24 hours",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "(histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{method=~\"$method\", namespace=\"truefoundry\", container=~\"servicefoundry-server.*\"}[24h])) by (le, path, method)) * 1000) > 300"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "round(sum(rate(container_cpu_usage_seconds_total{namespace=\"truefoundry\",container!=\"POD\",container!=\"\", container=~\"servicefoundry-server.*\"}[$__rate_interval])), 0.001)",
       "legendFormat": "Used"
      },
      {
       "expr": "round(sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"cpu\",namespace=\"truefoundry\",container=~\"servicefoundry-server.*\"}), 0.001)",
       "legendFormat": "Requested"
      },
      {
       "expr": "round(sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"cpu\",namespace=\"truefoundry\",container=~\"servicefoundry-server.*\"}), 0.001)",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "round((sum(container_memory_working_set_bytes{namespace=\"truefoundry\",container!=\"POD\",container!=\"\",pod!=\"\", container=~\"servicefoundry-server.*\"}))/1000000, 0.001)",
       "legendFormat": "Used"
      },
      {
       "expr": "round((sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"memory\",namespace=\"truefoundry\",container=~\"servicefoundry-server.*\"}))/1000000, 0.001)",
       "legendFormat": "Requested"
      },
      {
       "expr": "round((sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"memory\",namespace=\"truefoundry\",container=~\"ervicefoundry-server.*\"}))/1000000, 0.001)",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Pods",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "sum by (phase) (kube_pod_status_phase{namespace=\"truefoundry\", pod=~\"truefoundry-servicefoundry-server-.*\", job=\"kube-state-metrics\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "round((sum(rate(container_network_receive_bytes_total{namespace=\"truefoundry\",pod=~\"truefoundry-servicefoundry-server.*\"}[5m])))/1000000, 0.001)",
       "legendFormat": "Received"
      },
      {
       "expr": "round((sum(rate(container_network_transmit_bytes_total{namespace=\"truefoundry\",pod=~\"truefoundry-servicefoundry-server.*\"}[5m])))/1000000, 0.001)",
       "legendFormat": "Transmitted"
      }
     ]
    },
    {
     "title": "Disk IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "round((sum(rate(container_fs_reads_bytes_total{namespace=\"truefoundry\",container=~\"servicefoundry-server.*\",container=~\".*\"}[$__rate_interval])))/1000000, 0.001)",
       "legendFormat": "Read"
      },
      {
       "expr": "round((sum(rate(container_fs_writes_bytes_total{namespace=\"truefoundry\",container=~\"servicefoundry-server.*\",container=~\".*\"}[$__rate_interval])))/1000000, 0.001)",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Request duration percentiles in Milliseconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{path=~\"$path\", method=~\"$method\", namespace=\"truefoundry\",container=~\"servicefoundry-server.*\"}[$__rate_interval])) by (le)) * 1000",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{path=~\"$path\", method=~\"$method\", namespace=\"truefoundry\",container=~\"servicefoundry-server.*\"}[$__rate_interval])) by (le)) * 1000",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{path=~\"$path\", method=~\"$method\", namespace=\"truefoundry\",container=~\"servicefoundry-server.*\"}[$__rate_interval])) by (le)) * 1000",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{container=~\"servicefoundry-server.*\", path=~\"$path\", method=~\"$method\", namespace=\"truefoundry\"}[$__rate_interval]))",
       "legendFormat": "Request Rate"
      }
     ]
    },
    {
     "title": "Request Success Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{status_code!~\"^5..$\", container=~\"servicefoundry-server.*\", path=~\".*\", method=~\".*\", namespace=\"truefoundry\"}[$__rate_interval])) / sum (rate(http_request_duration_seconds_count{container=~\"servicefoundry-server.*\", path=~\".*\", method=~\".*\", namespace=\"truefoundry\"}[$__rate_interval])) * 100",
       "legendFormat": "Success Rate"
      }
     ]
    },
    {
     "title": "Sequelize Waiting Time to acquire Pool (in seconds)",
     "type": "timeseries",
     "description": "It is global i.e. for all queries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(sequelize_pool_acquire_wait_time_bucket{container=~\"servicefoundry-server.*\", namespace=\"truefoundry\"}[$__rate_interval])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(sequelize_pool_acquire_wait_time_bucket{container=~\"servicefoundry-server.*\", namespace=\"truefoundry\"}[$__rate_interval])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(sequelize_pool_acquire_wait_time_bucket{container=~\"servicefoundry-server.*\", namespace=\"truefoundry\"}[$__rate_interval])) by (le))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Rate of Requests by Response Code",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum (rate(http_request_duration_seconds_count{status_code=~\"^2..$\", container=~\"servicefoundry-server.*\", path=~\"$path\", method=~\"$method\", namespace=\"truefoundry\"}[$__rate_interval]))",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum (rate(http_request_duration_seconds_count{status_code=~\"^3..$\", container=~\"servicefoundry-server.*\", path=~\"$path\", method=~\"$method\", namespace=\"truefoundry\"}[$__rate_interval]))",
       "legendFormat": "3xx"
      },
      {
       "expr": "sum (rate(http_request_duration_seconds_count{status_code=~\"^4..$\", container=~\"servicefoundry-server.*\", path=~\"$path\", method=~\"$method\", namespace=\"truefoundry\"}[$__rate_interval]))",
       "legendFormat": "4xx"
      },
      {
       "expr": "sum by (status_code) (rate(http_request_duration_seconds_count{status_code=~\"^5..$\", container=~\"servicefoundry-server.*\", path=~\"$path\", method=~\"$method\", namespace=\"truefoundry\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "{namespace=\"truefoundry\", container!=\"init\",  container!=\"wait\", container=~\"servicefoundry-server.*\", stream=~\"$stream\"} |= \"$query\""
      }
     ]
    }
   ]
  },
  {
   "title": "TFY Controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "sum by (phase) (kube_pod_status_phase{namespace=\"truefoundry\", pod=~\"truefoundry-tfy-controller-.*\",job=\"kube-state-metrics\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "targets": [
      {
       "expr": "round((sum(container_memory_working_set_bytes{namespace=\"truefoundry\",container!=\"POD\",container!=\"\",pod!=\"\", container=~\"tfy-controller.*\"}))/1000000, 0.001)",
       "legendFormat": "Used"
      },
      {
       "expr": "round((sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"memory\",namespace=\"truefoundry\",container=~\"tfy-controller.*\"}))/1000000, 0.001)",
       "legendFormat": "Requested"
      },
      {
       "expr": "round((sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"memory\",namespace=\"truefoundry\",container=~\"tfy-controller.*\"}))/1000000, 0.001)",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "round(sum(rate(container_cpu_usage_seconds_total{namespace=\"truefoundry\",container!=\"POD\",container!=\"\", container=~\"tfy-controller.*\"}[$__rate_interval])), 0.001)",
       "legendFormat": "Used"
      },
      {
       "expr": "round(sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"cpu\",namespace=\"truefoundry\",container=~\"tfy-controller.*\"}), 0.001)",
       "legendFormat": "Requested"
      },
      {
       "expr": "round(sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"cpu\",namespace=\"truefoundry\",container=~\"tfy-controller.*\"}), 0.001)",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Disk IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "targets": [
      {
       "expr": "round((sum(rate(container_fs_reads_bytes_total{namespace=\"truefoundry\",container=~\"tfy-controller.*\",container=~\".*\"}[$__rate_interval])))/1000000, 0.001)",
       "legendFormat": "Read"
      },
      {
       "expr": "round((sum(rate(container_fs_writes_bytes_total{namespace=\"truefoundry\",container=~\"tfy-controller.*\",container=~\".*\"}[$__rate_interval])))/1000000, 0.001)",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Network Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "round((sum(rate(container_network_receive_bytes_total{namespace=\"truefoundry\",pod=~\"truefoundry-tfy-controller.*\"}[5m])))/1000000, 0.001)",
       "legendFormat": "Received"
      },
      {
       "expr": "round((sum(rate(container_network_transmit_bytes_total{namespace=\"truefoundry\",pod=~\"truefoundry-tfy-controller.*\"}[5m])))/1000000, 0.001)",
       "legendFormat": "Transmitted"
      }
     ]
    },
    {
     "title": "TASBP Message processing time MS percentile",
     "type": "timeseries",
     "description": "TFY Agent State Buffer Processor\nMessage processing time in MS",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(tfy_agent_state_buffer_processor_message_processing_time_ns_bucket[$__rate_interval])) by (le)) * 1e-6",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(tfy_agent_state_buffer_processor_message_processing_time_ns_bucket[$__rate_interval])) by (le)) * 1e-6",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.70, sum(rate(tfy_agent_state_buffer_processor_message_processing_time_ns_bucket[$__rate_interval])) by (le)) * 1e-6",
       "legendFormat": "p70"
      }
     ]
    },
    {
     "title": "TASBP Message processing rate",
     "type": "timeseries",
     "description": "TFY Agent State Buffer Processor\nMessage processing rate",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": "sum by (status) (rate(tfy_agent_state_buffer_processor_message_processed[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TASBP Message processing success %",
     "type": "timeseries",
     "description": "TFY Agent State Buffer Processor\nMessage processing success %",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "targets": [
      {
       "expr": "((sum(rate(tfy_agent_state_buffer_processor_message_processed{status=\"success\"}[$__rate_interval])) + 0.00000001 ) / (sum(rate(tfy_agent_state_buffer_processor_message_processed[$__rate_interval])) + 0.00000001)) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Logs Volume with Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 84 },
     "targets": [
      {
       "expr": "sum(count_over_time({namespace=\"truefoundry\", container!=\"init\",  container!=\"wait\", container=\"tfy-controller\", stream=~\"$stream\"} |= \"$query\" [$__interval]))"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 92 },
     "targets": [
      {
       "expr": "{namespace=\"truefoundry\", container!=\"init\",  container!=\"wait\", container=~\"tfy-controller.*\", stream=~\"$stream\"} |= \"$query\""
      }
     ]
    }
   ]
  },
  {
   "title": "MLFoundry Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "sum by (phase) (kube_pod_status_phase{namespace=\"truefoundry\", pod=~\"truefoundry-mlfoundry-server.*\",job=\"kube-state-metrics\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "targets": [
      {
       "expr": "round((sum(container_memory_working_set_bytes{namespace=\"truefoundry\",container!=\"POD\",container!=\"\",pod!=\"\", container=~\"mlfoundry-server.*\"}))/1000000, 0.001)",
       "legendFormat": "Used"
      },
      {
       "expr": "round((sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"memory\",namespace=\"truefoundry\",container=~\"mlfoundry-server.*\"}))/1000000, 0.001)",
       "legendFormat": "Requested"
      },
      {
       "expr": "round((sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"memory\",namespace=\"truefoundry\",container=~\"mlfoundry-server.*\"}))/1000000, 0.001)",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "round(sum(rate(container_cpu_usage_seconds_total{namespace=\"truefoundry\",container!=\"POD\",container!=\"\", container=~\"mlfoundry-server.*\"}[$__rate_interval])), 0.001)",
       "legendFormat": "Used"
      },
      {
       "expr": "round(sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"cpu\",namespace=\"truefoundry\",container=~\"mlfoundry-server.*\"}), 0.001)",
       "legendFormat": "Requested"
      },
      {
       "expr": "round(sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"cpu\",namespace=\"truefoundry\",container=~\"mlfoundry-server.*\"}), 0.001)",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Disk IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "targets": [
      {
       "expr": "round((sum(rate(container_fs_reads_bytes_total{namespace=\"truefoundry\",container=~\"mlfoundry-server.*\",container=~\".*\"}[$__rate_interval])))/1000000, 0.001)",
       "legendFormat": "Read"
      },
      {
       "expr": "round((sum(rate(container_fs_writes_bytes_total{namespace=\"truefoundry\",container=~\"mlfoundry-server.*\",container=~\".*\"}[$__rate_interval])))/1000000, 0.001)",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Network Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "targets": [
      {
       "expr": "round((sum(rate(container_network_receive_bytes_total{namespace=\"truefoundry\",pod=~\"truefoundry-mlfoundry-server.*\"}[5m])))/1000000, 0.001)",
       "legendFormat": "Received"
      },
      {
       "expr": "round((sum(rate(container_network_transmit_bytes_total{namespace=\"truefoundry\",pod=~\"truefoundry-mlfoundry-server.*\"}[5m])))/1000000, 0.001)",
       "legendFormat": "Transmitted"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
     "targets": [
      {
       "expr": "{namespace=\"truefoundry\", container!=\"init\",  container!=\"wait\", container=~\"mlfoundry-server.*\", stream=~\"$stream\"} |= \"$query\""
      }
     ]
    }
   ]
  },
  {
   "title": "LLM Gateway Infra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "round((sum(container_memory_working_set_bytes{namespace=\"truefoundry\",container!=\"POD\",container!=\"\",pod!=\"\",container=~\"tfy-llm-gateway.*\", pod!~\".*infra.*\"}))/1000000, 0.001)",
       "legendFormat": "Used"
      },
      {
       "expr": "round((sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"memory\",namespace=\"truefoundry\",container=~\"tfy-llm-gateway.*\", pod!~\".*infra.*\"}))/1000000, 0.001)",
       "legendFormat": "Requested"
      },
      {
       "expr": "round((sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"memory\",namespace=\"truefoundry\",container=~\"tfy-llm-gateway.*\", pod!~\".*infra.*\"}))/1000000, 0.001)",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "round((sum(container_memory_working_set_bytes{namespace=\"truefoundry\",container!=\"POD\",container!=\"\",pod!=\"\",container=~\"tfy-llm-gateway.*\", pod!~\".*infra.*\"}))/1000000, 0.001)",
       "legendFormat": "Used"
      },
      {
       "expr": "round((sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"memory\",namespace=\"truefoundry\",container=~\"tfy-llm-gateway.*\", pod!~\".*infra.*\"}))/1000000, 0.001)",
       "legendFormat": "Requested"
      },
      {
       "expr": "round((sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"memory\",namespace=\"truefoundry\",container=~\"tfy-llm-gateway.*\", pod!~\".*infra.*\"}))/1000000, 0.001)",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Pods",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "sum by (phase) (kube_pod_status_phase{namespace=\"truefoundry\", pod=~\"tfy-llm-gateway.*\", pod!~\".*infra.*\", job=\"kube-state-metrics\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{container=\"tfy-llm-gateway\", path=~\"$path\", method=~\"$method\", namespace=\"truefoundry\"}[$__rate_interval]))",
       "legendFormat": "Request Rate"
      }
     ]
    },
    {
     "title": "Request Success Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{status_code!~\"^5..$\", container=\"tfy-llm-gateway\", path=~\".*\", method=~\".*\", namespace=\"truefoundry\"}[$__rate_interval])) / sum (rate(http_request_duration_seconds_count{container=\"tfy-llm-gateway\", path=~\".*\", method=~\".*\", namespace=\"truefoundry\"}[$__rate_interval])) * 100",
       "legendFormat": "Success Rate"
      }
     ]
    },
    {
     "title": "Rate of Requests by Response Code",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum (rate(http_request_duration_seconds_count{status_code=~\"^2..$\", container=\"tfy-llm-gateway\", path=~\"$path\", method=~\"$method\", namespace=\"truefoundry\"}[$__rate_interval]))",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum (rate(http_request_duration_seconds_count{status_code=~\"^3..$\", container=\"tfy-llm-gateway\", path=~\"$path\", method=~\"$method\", namespace=\"truefoundry\"}[$__rate_interval]))",
       "legendFormat": "3xx"
      },
      {
       "expr": "sum (rate(http_request_duration_seconds_count{status_code=~\"^4..$\", container=\"tfy-llm-gateway\", path=~\"$path\", method=~\"$method\", namespace=\"truefoundry\"}[$__rate_interval]))",
       "legendFormat": "4xx"
      },
      {
       "expr": "sum by (status_code) (rate(http_request_duration_seconds_count{status_code=~\"^5..$\", container=\"tfy-llm-gateway\", path=~\"$path\", method=~\"$method\", namespace=\"truefoundry\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "{namespace=\"truefoundry\", container!=\"init\",  container!=\"wait\", container=~\"tfy-llm-gateway.*\", stream=~\"$stream\"} |= \"$query\""
      }
     ]
    }
   ]
  },
  {
   "title": "Sfy Manifest Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "round(sum(rate(container_cpu_usage_seconds_total{namespace=\"truefoundry\",container!=\"POD\",container!=\"\", container=~\"sfy-manifest-service.*\"}[$__rate_interval])), 0.001)",
       "legendFormat": "Used"
      },
      {
       "expr": "round(sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"cpu\",namespace=\"truefoundry\",container=~\"sfy-manifest-service.*\"}), 0.001)",
       "legendFormat": "Requested"
      },
      {
       "expr": "round(sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"cpu\",namespace=\"truefoundry\",container=~\"sfy-manifest-service.*\"}), 0.001)",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "round((sum(container_memory_working_set_bytes{namespace=\"truefoundry\",container!=\"POD\",container!=\"\",pod!=\"\", container=~\"sfy-manifest-service.*\"}))/1000000, 0.001)",
       "legendFormat": "Used"
      },
      {
       "expr": "round((sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"memory\",namespace=\"truefoundry\",container=~\"sfy-manifest-service.*\"}))/1000000, 0.001)",
       "legendFormat": "Requested"
      },
      {
       "expr": "round((sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"memory\",namespace=\"truefoundry\",container=~\"sfy-manifest-service.*\"}))/1000000, 0.001)",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Request duration percentiles in Milliseconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_bucket{namespace=\"truefoundry\", container=\"sfy-manifest-service\"}[$__rate_interval])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_bucket{namespace=\"truefoundry\", container=\"sfy-manifest-service\"}[$__rate_interval])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_bucket{namespace=\"truefoundry\", container=\"sfy-manifest-service\"}[$__rate_interval])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Disk IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "round((sum(rate(container_fs_reads_bytes_total{namespace=\"truefoundry\",container=~\"sfy-manifest-service.*\",container=~\".*\"}[$__rate_interval])))/1000000, 0.001)",
       "legendFormat": "Read"
      },
      {
       "expr": "round((sum(rate(container_fs_writes_bytes_total{namespace=\"truefoundry\",container=~\"sfy-manifest-service.*\",container=~\".*\"}[$__rate_interval])))/1000000, 0.001)",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Request Success Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "(sum(rate(http_requests_total{namespace=\"truefoundry\", container=\"sfy-manifest-service\", code!~\"5.*\"}[$__rate_interval])) + 0.00000001) / (sum(rate(http_requests_total{namespace=\"truefoundry\", container=\"sfy-manifest-service\"}[$__rate_interval])) + 0.00000001) * 100",
       "legendFormat": "Success Rate"
      }
     ]
    },
    {
     "title": "Network Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "expr": "round((sum(rate(container_network_receive_bytes_total{namespace=\"truefoundry\",pod=~\"truefoundry-sfy-manifest-service.*\"}[5m])))/1000000, 0.001)",
       "legendFormat": "Received"
      },
      {
       "expr": "round((sum(rate(container_network_transmit_bytes_total{namespace=\"truefoundry\",pod=~\"truefoundry-sfy-manifest-service.*\"}[5m])))/1000000, 0.001)",
       "legendFormat": "Transmitted"
      }
     ]
    },
    {
     "title": "Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "sum(rate(http_requests_total{namespace=\"truefoundry\", container=\"sfy-manifest-service\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Pods",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "expr": "sum by (phase) (kube_pod_status_phase{namespace=\"truefoundry\", pod=~\"truefoundry-sfy-manifest-service-.*\", job=\"kube-state-metrics\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate of Requests by Response Code",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "sum(rate(http_requests_total{namespace=\"truefoundry\", container=\"sfy-manifest-service\", code=~\"2.*\"}[$__rate_interval]))",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum by (code) (rate(http_requests_total{namespace=\"truefoundry\", container=\"sfy-manifest-service\", code!~\"2.*\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Logs Volume with Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "targets": [
      {
       "expr": "sum(count_over_time({namespace=\"truefoundry\", container!=\"init\",  container!=\"wait\", container=~\"sfy-manifest-service.*\", stream=~\"$stream\"} |= \"$query\" [$__interval]))"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "{namespace=\"truefoundry\", container!=\"init\",  container!=\"wait\", container=~\"sfy-manifest-service.*\", stream=~\"$stream\"} |= \"$query\""
      }
     ]
    }
   ]
  },
  {
   "title": "K8s Controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "round(sum(rate(container_cpu_usage_seconds_total{namespace=\"truefoundry\",container!=\"POD\",container!=\"\", container=~\"tfy-k8s-controller.*\"}[$__rate_interval])), 0.001)",
       "legendFormat": "Used"
      },
      {
       "expr": "round(sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"cpu\",namespace=\"truefoundry\",container=~\"tfy-k8s-controller.*\"}), 0.001)",
       "legendFormat": "Requested"
      },
      {
       "expr": "round(sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"cpu\",namespace=\"truefoundry\",container=~\"tfy-k8s-controller.*\"}), 0.001)",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "targets": [
      {
       "expr": "round((sum(container_memory_working_set_bytes{namespace=\"truefoundry\",container!=\"POD\",container!=\"\",pod!=\"\", container=~\"tfy-k8s-controller.*\"}))/1000000, 0.001)",
       "legendFormat": "Used"
      },
      {
       "expr": "round((sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"memory\",namespace=\"truefoundry\",container=~\"tfy-k8s-controller.*\"}))/1000000, 0.001)",
       "legendFormat": "Requested"
      },
      {
       "expr": "round((sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"memory\",namespace=\"truefoundry\",container=~\"tfy-k8s-controller.*\"}))/1000000, 0.001)",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Disk IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "round((sum(rate(container_fs_reads_bytes_total{namespace=\"truefoundry\",container=~\"tfy-k8s-controller.*\",container=~\".*\"}[$__rate_interval])))/1000000, 0.001)",
       "legendFormat": "Read"
      },
      {
       "expr": "round((sum(rate(container_fs_writes_bytes_total{namespace=\"truefoundry\",container=~\"tfy-k8s-controller.*\",container=~\".*\"}[$__rate_interval])))/1000000, 0.001)",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Network Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "targets": [
      {
       "expr": "round((sum(rate(container_network_receive_bytes_total{namespace=\"truefoundry\",pod=~\"truefoundry-tfy-k8s-controller.*\"}[5m])))/1000000, 0.001)",
       "legendFormat": "Received"
      },
      {
       "expr": "round((sum(rate(container_network_transmit_bytes_total{namespace=\"truefoundry\",pod=~\"truefoundry-tfy-k8s-controller.*\"}[5m])))/1000000, 0.001)",
       "legendFormat": "Transmitted"
      }
     ]
    },
    {
     "title": "Pods",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "sum by (phase) (kube_pod_status_phase{namespace=\"truefoundry\", pod=~\"truefoundry-tfy-k8s-controller-.*\", job=\"kube-state-metrics\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
     "targets": [
      {
       "expr": "{namespace=\"truefoundry\", container!=\"init\",  container!=\"wait\", container=~\"tfy-k8s-controller.*\", stream=~\"$stream\"} |= \"$query\""
      }
     ]
    }
   ]
  },
  {
   "title": "Frontend App",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "sum by (phase) (kube_pod_status_phase{namespace=\"truefoundry\", pod=~\"truefoundry-truefoundry-frontend-app-.*\",job=\"kube-state-metrics\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "targets": [
      {
       "expr": "round((sum(container_memory_working_set_bytes{namespace=\"truefoundry\",container!=\"POD\",container!=\"\",pod!=\"\", container=~\"truefoundry-frontend-app.*\"}))/1000000, 0.001)",
       "legendFormat": "Used"
      },
      {
       "expr": "round((sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"memory\",namespace=\"truefoundry\",container=~\"truefoundry-frontend-app.*\"}))/1000000, 0.001)",
       "legendFormat": "Requested"
      },
      {
       "expr": "round((sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"memory\",namespace=\"truefoundry\",container=~\"truefoundry-frontend-app.*\"}))/1000000, 0.001)",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "targets": [
      {
       "expr": "round(sum(rate(container_cpu_usage_seconds_total{namespace=\"truefoundry\",container!=\"POD\",container!=\"\", container=~\"truefoundry-frontend-app.*\"}[$__rate_interval])), 0.001)",
       "legendFormat": "Used"
      },
      {
       "expr": "round(sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"cpu\",namespace=\"truefoundry\",container=~\"truefoundry-frontend-app.*\"}), 0.001)",
       "legendFormat": "Requested"
      },
      {
       "expr": "round(sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"cpu\",namespace=\"truefoundry\",container=~\"truefoundry-frontend-app.*\"}), 0.001)",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Disk IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
     "targets": [
      {
       "expr": "round((sum(rate(container_fs_reads_bytes_total{namespace=\"truefoundry\",container=~\"truefoundry-frontend-app.*\",container=~\".*\"}[$__rate_interval])))/1000000, 0.001)",
       "legendFormat": "Read"
      },
      {
       "expr": "round((sum(rate(container_fs_writes_bytes_total{namespace=\"truefoundry\",container=~\"truefoundry-frontend-app.*\",container=~\".*\"}[$__rate_interval])))/1000000, 0.001)",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Network Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
     "targets": [
      {
       "expr": "round((sum(rate(container_network_receive_bytes_total{namespace=\"truefoundry\",pod=~\"truefoundry-truefoundry-frontend-app.*\"}[5m])))/1000000, 0.001)",
       "legendFormat": "Received"
      },
      {
       "expr": "round((sum(rate(container_network_transmit_bytes_total{namespace=\"truefoundry\",pod=~\"truefoundry-truefoundry-frontend-app.*\"}[5m])))/1000000, 0.001)",
       "legendFormat": "Transmitted"
      }
     ]
    },
    {
     "title": "Success Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
     "targets": [
      {
       "expr": "round(100*sum(rate(istio_requests_total{destination_service_namespace=~\"truefoundry\", destination_service_name=~\"truefoundry-truefoundry-frontend-app\",response_code!~\"5.*\"}[$__rate_interval])) / sum(rate(istio_requests_total{destination_service_namespace=~\"truefoundry\",destination_service_name=~\"truefoundry-truefoundry-frontend-app\"}[$__rate_interval])), 0.001)",
       "legendFormat": " {{pod}}"
      }
     ]
    },
    {
     "title": "Request Volume",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
     "targets": [
      {
       "expr": "round(sum(rate(istio_requests_total{destination_service_namespace=~\"truefoundry\", destination_service_name=~\"truefoundry-truefoundry-frontend-app\"}[$__rate_interval])), 0.001)",
       "legendFormat": " {{pod}}"
      }
     ]
    },
    {
     "title": "Requests By Response Code",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
     "targets": [
      {
       "expr": "round(sum(rate(istio_requests_total{destination_service_namespace=~\"truefoundry\",destination_service_name=~\"truefoundry-truefoundry-frontend-app\"}[$__rate_interval])) by (destination_service_name, destination_service_namespace, response_code), 0.001)",
       "legendFormat": " {{response_code}}"
      }
     ]
    },
    {
     "title": "Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
     "targets": [
      {
       "expr": "round(histogram_quantile(0.50, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_namespace=~\"truefoundry\", destination_service_name=~\"truefoundry-truefoundry-frontend-app\"}[$__rate_interval])) by (le)), 0.001)",
       "legendFormat": "P50 {{pod}}"
      },
      {
       "expr": "round(histogram_quantile(0.90, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_namespace=~\"truefoundry\", destination_service_name=~\"truefoundry-truefoundry-frontend-app\"}[$__rate_interval])) by (le)), 0.001)",
       "legendFormat": "P90 {{pod}}"
      },
      {
       "expr": "round(histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_namespace=~\"truefoundry\", destination_service_name=~\"truefoundry-truefoundry-frontend-app\"}[$__rate_interval])) by (le)), 0.001)",
       "legendFormat": "P99 {{pod}}"
      }
     ]
    },
    {
     "title": "Logs Volume with Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
     "targets": [
      {
       "expr": "sum(count_over_time({namespace=\"truefoundry\", container!=\"init\",  container!=\"wait\", container=~\"truefoundry-frontend-app.*\", stream=~\"$stream\"} |= \"$query\" [$__interval]))"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 104 },
     "targets": [
      {
       "expr": "{namespace=\"truefoundry\", container!=\"init\",  container!=\"wait\", container=~\"truefoundry-frontend-app.*\", stream=~\"$stream\"} |= \"$query\""
      }
     ]
    }
   ]
  }
 ]
}