{
 "title": "truefoundry-deltafusion-query-server",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "query", "label": "Search Query" },
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "DS_VICTORIALOGS",
    "label": "VictoriaLogs",
    "query": "victoriametrics-logs-datasource"
   },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "podpattern",
    "label": "Pod Pattern",
    "query": "truefoundry-deltafusion-query-server.*"
   },
   { "name": "app_kubernetes_io_name", "label": "app_kubernetes_io_name", "query": "deltafusion-query-server" }
  ]
 },
 "panels": [
  { "title": "CPU, Memory, Network, Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "round(sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"POD\",container!=\"\", pod=~\"$podpattern\"}[$__rate_interval])), 0.001)",
     "legendFormat": "Used"
    },
    {
     "expr": "round(sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"cpu\",namespace=\"$namespace\",pod=~\"$podpattern\"}), 0.001)",
     "legendFormat": "Requested"
    },
    {
     "expr": "round(sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"cpu\",namespace=\"$namespace\",pod=~\"$podpattern\"}), 0.001)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "round((sum(container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"POD\",container!=\"\",pod!=\"\", pod=~\"$podpattern\"}))/1000000, 0.001)",
     "legendFormat": "Used"
    },
    {
     "expr": "round((sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"memory\",namespace=\"$namespace\",pod=~\"$podpattern\"}))/1000000, 0.001)",
     "legendFormat": "Requested"
    },
    {
     "expr": "round((sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"memory\",namespace=\"$namespace\",pod=~\"$podpattern\"}))/1000000, 0.001)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Network Usage (Megabytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "round(sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval])) / 1000000, 0.001)",
     "legendFormat": "Received"
    },
    {
     "expr": "round(sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval])) / 1000000, 0.001)",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Network per CPU (MB/s / CPU)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "round(sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval])) / 1000000, 0.001) / round(sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"POD\",container!=\"\", pod=~\"$podpattern\"}[$__rate_interval])), 0.001)",
     "legendFormat": "Received"
    },
    {
     "expr": "round(sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval])) / 1000000, 0.001) / round(sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"POD\",container!=\"\", pod=~\"$podpattern\"}[$__rate_interval])), 0.001)",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "round(sum(rate(container_fs_reads_bytes_total{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval])) / 1000000, 0.001)",
     "legendFormat": "Read"
    },
    {
     "expr": "round(sum(rate(container_fs_writes_bytes_total{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval])) / 1000000, 0.001)",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Peak and P50 CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "round(max_over_time(sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"POD\",container!=\"\", pod=~\"$podpattern\"}[$__rate_interval]))[10m:15s]), 0.001)",
     "legendFormat": "UsedPeak"
    },
    {
     "expr": "round(quantile_over_time(0.5, sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"POD\",container!=\"\", pod=~\"$podpattern\"}[$__rate_interval]))[10m:15s]), 0.001)",
     "legendFormat": "UsedP50"
    },
    {
     "expr": "round(sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"cpu\",namespace=\"$namespace\",pod=~\"$podpattern\"}), 0.001)",
     "legendFormat": "Requested"
    },
    {
     "expr": "round(sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"cpu\",namespace=\"$namespace\",pod=~\"$podpattern\"}), 0.001)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "\nround((max by (container) (\n  max by (namespace, pod, container) (\n    rate(\n      container_cpu_cfs_throttled_periods_total{\n        job=\"kubelet\",\n        container!=\"\", container!=\"POD\", container!=\"init\", container!=\"wait\",\n        namespace=\"$namespace\", pod!=\"\", pod=~\"$podpattern\"\n      }[$__rate_interval]\n    )\n    /\n    rate(\n      container_cpu_cfs_periods_total{\n        job=\"kubelet\",\n        container!=\"\", container!=\"POD\", container!=\"init\", container!=\"wait\",\n        namespace=\"$namespace\", pod!=\"\", pod=~\"$podpattern\"\n      }[$__rate_interval]\n    )\n  )\n)) * 100, 1)",
     "legendFormat": " {{container}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests By Response Code",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 334 },
     "targets": [
      {
       "expr": "round(sum(rate(http_requests_total{container=\"$app_kubernetes_io_name\", endpoint=~\".*\", method=~\".*\", namespace=\"$namespace\"}[$__rate_interval])) by (status), 0.001)",
       "legendFormat": " {{status}}"
      }
     ]
    },
    {
     "title": "Request Duration (seconds)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 334 },
     "targets": [
      {
       "expr": "round(histogram_quantile(0.50, sum(rate(http_requests_duration_seconds_bucket{container=\"$app_kubernetes_io_name\", endpoint=~\".*\", method=~\".*\", namespace=\"$namespace\"}[$__rate_interval])) by (le)), 0.001)",
       "legendFormat": "P50 {{pod}}"
      },
      {
       "expr": "round(histogram_quantile(0.90, sum(rate(http_requests_duration_seconds_bucket{container=\"$app_kubernetes_io_name\", endpoint=~\".*\", method=~\".*\", namespace=\"$namespace\"}[$__rate_interval])) by (le)), 0.001)",
       "legendFormat": "P90 {{pod}}"
      },
      {
       "expr": "round(histogram_quantile(0.99, sum(rate(http_requests_duration_seconds_bucket{container=\"$app_kubernetes_io_name\", endpoint=~\".*\", method=~\".*\", namespace=\"$namespace\"}[$__rate_interval])) by (le)), 0.001)",
       "legendFormat": "P99 {{pod}}"
      }
     ]
    },
    {
     "title": "Request Volume",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 390 },
     "targets": [
      {
       "expr": "round(sum(rate(http_requests_total{container=\"$app_kubernetes_io_name\", endpoint=~\".*\", method=~\".*\", namespace=\"$namespace\"}[$__rate_interval])), 0.001)",
       "legendFormat": " {{pod}}"
      }
     ]
    },
    {
     "title": "Success Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 390 },
     "targets": [
      {
       "expr": "sum(rate(http_requests_total{status!~\"^5..$\", container=\"$app_kubernetes_io_name\", endpoint=~\".*\", method=~\".*\", namespace=\"$namespace\"}[$__rate_interval])) / sum (rate(http_requests_total{container=\"$app_kubernetes_io_name\", endpoint=~\".*\", method=~\".*\", namespace=\"$namespace\"}[$__rate_interval])) * 100",
       "legendFormat": " {{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "Foyer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Hybrid Cache Operation Latency (p50, p95) (MS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(foyer_hybrid_op_duration_bucket{namespace=\"$namespace\", pod=~\"$podpattern\", container=\"$app_kubernetes_io_name\"}[$__rate_interval])) by (le, op)) * 1000",
     "legendFormat": "p50 {{op}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(foyer_hybrid_op_duration_bucket{namespace=\"$namespace\", pod=~\"$podpattern\", container=\"$app_kubernetes_io_name\"}[$__rate_interval])) by (le, op)) * 1000",
     "legendFormat": "p95 {{op}}"
    }
   ]
  },
  {
   "title": "Storage Operation Latency (p50, p95) (sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(foyer_storage_op_duration_bucket{namespace=\"$namespace\", pod=~\"$podpattern\", container=\"$app_kubernetes_io_name\"}[$__rate_interval])) by (le, op))",
     "legendFormat": "p50 {{op}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(foyer_storage_op_duration_bucket{namespace=\"$namespace\", pod=~\"$podpattern\", container=\"$app_kubernetes_io_name\"}[$__rate_interval])) by (le, op))",
     "legendFormat": "p95 {{op}}"
    }
   ]
  },
  {
   "title": "Memory Cache Operations (ops/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum(rate(foyer_memory_op_total{namespace=\"$namespace\", pod=~\"$podpattern\", container=\"$app_kubernetes_io_name\"}[$__rate_interval])) by (op)",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "Hybrid Cache Throughput (ops/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum(rate(foyer_hybrid_op_total{namespace=\"$namespace\", pod=~\"$podpattern\", container=\"$app_kubernetes_io_name\"}[$__rate_interval])) by (op)",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "Disk I/O (MB/sec) (read/write)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum(rate(foyer_storage_disk_io_bytes{namespace=\"$namespace\", pod=~\"$podpattern\", container=\"$app_kubernetes_io_name\", op=~\"read|write\"}[$__rate_interval])) by (op) / 1024 / 1024",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "LODC Recover Latency (p50, p95) (sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(foyer_storage_lodc_recover_duration_bucket{namespace=\"$namespace\", pod=~\"$podpattern\", container=\"$app_kubernetes_io_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50 recover"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(foyer_storage_lodc_recover_duration_bucket{namespace=\"$namespace\", pod=~\"$podpattern\", container=\"$app_kubernetes_io_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95 recover"
    }
   ]
  },
  {
   "title": "Entry Serde Latency (p50, p95) (sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(foyer_storage_entry_serde_duration_bucket{namespace=\"$namespace\", pod=~\"$podpattern\", container=\"$app_kubernetes_io_name\"}[$__rate_interval])) by (le, op))",
     "legendFormat": "p50 {{op}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(foyer_storage_entry_serde_duration_bucket{namespace=\"$namespace\", pod=~\"$podpattern\", container=\"$app_kubernetes_io_name\"}[$__rate_interval])) by (le, op))",
     "legendFormat": "p95 {{op}}"
    }
   ]
  },
  {
   "title": "LODC Buffer Efficiency (p50, p95) (sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(foyer_storage_lodc_buffer_efficiency_bucket{namespace=\"$namespace\", pod=~\"$podpattern\", container=\"$app_kubernetes_io_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50 efficiency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(foyer_storage_lodc_buffer_efficiency_bucket{namespace=\"$namespace\", pod=~\"$podpattern\", container=\"$app_kubernetes_io_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95 efficiency"
    }
   ]
  },
  {
   "title": "Memory Usage (MB)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(foyer_memory_usage{namespace=\"$namespace\", pod=~\"$podpattern\", container=\"$app_kubernetes_io_name\"}) / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Storage Cache Operations (ops/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "sum(rate(foyer_storage_op_total{namespace=\"$namespace\", pod=~\"$podpattern\", container=\"$app_kubernetes_io_name\"}[$__rate_interval])) by (op)",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "Disk I/O Latency (p50, p95) (sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(foyer_storage_disk_io_duration_bucket{namespace=\"$namespace\", pod=~\"$podpattern\", container=\"$app_kubernetes_io_name\"}[$__rate_interval])) by (le, op))",
     "legendFormat": "p50 {{op}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(foyer_storage_disk_io_duration_bucket{namespace=\"$namespace\", pod=~\"$podpattern\", container=\"$app_kubernetes_io_name\"}[$__rate_interval])) by (le, op))",
     "legendFormat": "p95 {{op}}"
    }
   ]
  },
  {
   "title": "Inner Op Latency (p50, p95) (sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(foyer_storage_inner_op_duration_bucket{namespace=\"$namespace\", pod=~\"$podpattern\", container=\"$app_kubernetes_io_name\"}[$__rate_interval])) by (le, op))",
     "legendFormat": "p50 {{op}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(foyer_storage_inner_op_duration_bucket{namespace=\"$namespace\", pod=~\"$podpattern\", container=\"$app_kubernetes_io_name\"}[$__rate_interval])) by (le, op))",
     "legendFormat": "p95 {{op}}"
    }
   ]
  },
  { "title": "Pods and Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Pod Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "max_over_time(sum(kube_pod_status_phase{namespace=\"$namespace\", job=\"kube-state-metrics\", pod=~\"$podpattern\"}) by (phase)[$__rate_interval:])",
     "legendFormat": " {{phase}}"
    }
   ]
  },
  {
   "title": "Logs Volume with Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "namespace:\"$namespace\" -container:(\"wait\" OR \"init\") app_kubernetes_io_name:\"$app_kubernetes_io_name\" ~\"$query\" | count()\n\n"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "namespace:\"$namespace\" -container:(\"wait\" OR \"init\") app_kubernetes_io_name:\"$app_kubernetes_io_name\" ~\"$query\""
    }
   ]
  }
 ]
}