{
 "title": "truefoundry-deltafusion-ingestor",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "query", "label": "Search Query" },
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "DS_VICTORIALOGS",
    "label": "VictoriaLogs",
    "query": "victoriametrics-logs-datasource"
   },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "podpattern",
    "label": "Pod Pattern",
    "query": "truefoundry-deltafusion-ingestor.*"
   },
   { "name": "app_kubernetes_io_name", "label": "app_kubernetes_io_name", "query": "deltafusion-ingestor" }
  ]
 },
 "panels": [
  { "title": "CPU, Memory, Network, Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "round(sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"POD\",container!=\"\", pod=~\"$podpattern\"}[$__rate_interval])), 0.001)",
     "legendFormat": "Used"
    },
    {
     "expr": "round(sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"cpu\",namespace=\"$namespace\",pod=~\"$podpattern\"}), 0.001)",
     "legendFormat": "Requested"
    },
    {
     "expr": "round(sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"cpu\",namespace=\"$namespace\",pod=~\"$podpattern\"}), 0.001)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "round((sum(container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"POD\",container!=\"\",pod!=\"\", pod=~\"$podpattern\"}))/1000000, 0.001)",
     "legendFormat": "Used"
    },
    {
     "expr": "round((sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"memory\",namespace=\"$namespace\",pod=~\"$podpattern\"}))/1000000, 0.001)",
     "legendFormat": "Requested"
    },
    {
     "expr": "round((sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"memory\",namespace=\"$namespace\",pod=~\"$podpattern\"}))/1000000, 0.001)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Network Usage (Megabytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "round(sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval])) / 1000000, 0.001)",
     "legendFormat": "Received"
    },
    {
     "expr": "round(sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval])) / 1000000, 0.001)",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "round(sum(rate(container_fs_reads_bytes_total{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval])) / 1000000, 0.001)",
     "legendFormat": "Read"
    },
    {
     "expr": "round(sum(rate(container_fs_writes_bytes_total{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval])) / 1000000, 0.001)",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Disk Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "((\n  kubelet_volume_stats_used_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\"data-$podpattern\"}\n)\n/\n(\n  kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\"data-$podpattern\"}\n)) * 100",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Peak and P50 CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "round(max_over_time(sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"POD\",container!=\"\", pod=~\"$podpattern\"}[$__rate_interval]))[10m:15s]), 0.001)",
     "legendFormat": "UsedPeak"
    },
    {
     "expr": "round(quantile_over_time(0.5, sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"POD\",container!=\"\", pod=~\"$podpattern\"}[$__rate_interval]))[10m:15s]), 0.001)",
     "legendFormat": "UsedP50"
    },
    {
     "expr": "round(sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"cpu\",namespace=\"$namespace\",pod=~\"$podpattern\"}), 0.001)",
     "legendFormat": "Requested"
    },
    {
     "expr": "round(sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"cpu\",namespace=\"$namespace\",pod=~\"$podpattern\"}), 0.001)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "\nround((max by (container) (\n  max by (namespace, pod, container) (\n    rate(\n      container_cpu_cfs_throttled_periods_total{\n        job=\"kubelet\",\n        container!=\"\", container!=\"POD\", container!=\"init\", container!=\"wait\",\n        namespace=\"$namespace\", pod!=\"\", pod=~\"$podpattern\"\n      }[$__rate_interval]\n    )\n    /\n    rate(\n      container_cpu_cfs_periods_total{\n        job=\"kubelet\",\n        container!=\"\", container!=\"POD\", container!=\"init\", container!=\"wait\",\n        namespace=\"$namespace\", pod!=\"\", pod=~\"$podpattern\"\n      }[$__rate_interval]\n    )\n  )\n)) * 100, 1)",
     "legendFormat": " {{container}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Requests By Response Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "round(sum(rate(http_requests_total{container=\"$app_kubernetes_io_name\", endpoint=~\".*\", method=~\".*\", namespace=\"$namespace\"}[$__rate_interval])) by (status), 0.001)",
     "legendFormat": " {{status}}"
    }
   ]
  },
  {
   "title": "Request Duration (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "round(histogram_quantile(0.50, sum(rate(http_requests_duration_seconds_bucket{container=\"$app_kubernetes_io_name\", endpoint=~\".*\", method=~\".*\", namespace=\"$namespace\"}[$__rate_interval])) by (le)), 0.001)",
     "legendFormat": "P50 {{pod}}"
    },
    {
     "expr": "round(histogram_quantile(0.90, sum(rate(http_requests_duration_seconds_bucket{container=\"$app_kubernetes_io_name\", endpoint=~\".*\", method=~\".*\", namespace=\"$namespace\"}[$__rate_interval])) by (le)), 0.001)",
     "legendFormat": "P90 {{pod}}"
    },
    {
     "expr": "round(histogram_quantile(0.99, sum(rate(http_requests_duration_seconds_bucket{container=\"$app_kubernetes_io_name\", endpoint=~\".*\", method=~\".*\", namespace=\"$namespace\"}[$__rate_interval])) by (le)), 0.001)",
     "legendFormat": "P99 {{pod}}"
    }
   ]
  },
  {
   "title": "Request Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "round(sum(rate(http_requests_total{container=\"$app_kubernetes_io_name\", endpoint=~\".*\", method=~\".*\", namespace=\"$namespace\"}[$__rate_interval])), 0.001)",
     "legendFormat": " {{pod}}"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status!~\"^5..$\", container=\"$app_kubernetes_io_name\", endpoint=~\".*\", method=~\".*\", namespace=\"$namespace\"}[$__rate_interval])) / sum (rate(http_requests_total{container=\"$app_kubernetes_io_name\", endpoint=~\".*\", method=~\".*\", namespace=\"$namespace\"}[$__rate_interval])) * 100",
     "legendFormat": " {{pod}}"
    }
   ]
  },
  { "title": "Ingestor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Rate of items count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum(rate(ingest_request_items_count{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Time to write items to disk (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(write_items_batch_to_disk_duration_seconds_bucket{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(write_spans_to_disk_duration_seconds_bucket{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval])) by (le))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(write_spans_to_disk_duration_seconds_bucket{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(write_spans_to_disk_duration_seconds_bucket{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Rate of files written to disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum(rate(files_written_to_disk_count{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval])) by (status)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of items per cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "(sum(rate(ingest_request_items_count{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval]))) / round(sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"POD\",container!=\"\", pod=~\"$podpattern\"}[$__rate_interval])), 0.001)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network per CPU (MB/s / CPU)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "round(sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval])) / 1000000, 0.001) / round(sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"POD\",container!=\"\", pod=~\"$podpattern\"}[$__rate_interval])), 0.001)",
     "legendFormat": "Received"
    },
    {
     "expr": "round(sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval])) / 1000000, 0.001) / round(sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"POD\",container!=\"\", pod=~\"$podpattern\"}[$__rate_interval])), 0.001)",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Rate of failure to flush to delta lake",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "sum(rate(flush_project_directory_to_delta_table_failure_count{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Flusher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Time to write project directory to delta table (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(flush_project_directory_to_delta_table_duration_seconds_bucket{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(flush_project_directory_to_delta_table_duration_seconds_bucket{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval])) by (le))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(flush_project_directory_to_delta_table_duration_seconds_bucket{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(flush_project_directory_to_delta_table_duration_seconds_bucket{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Total time to flush project directory (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(flush_project_directory_total_duration_seconds_bucket{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(flush_project_directory_total_duration_seconds_bucket{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval])) by (le))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(flush_project_directory_total_duration_seconds_bucket{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(flush_project_directory_total_duration_seconds_bucket{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Project Directory Flush With Lag (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(flush_project_directory_total_duration_with_lag_seconds_bucket{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(flush_project_directory_total_duration_with_lag_seconds_bucket{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval])) by (le))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(flush_project_directory_total_duration_with_lag_seconds_bucket{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(flush_project_directory_total_duration_with_lag_seconds_bucket{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(flush_project_directory_total_duration_with_lag_seconds_bucket{namespace=\"$namespace\", pod=~\"$podpattern\"}[$__rate_interval])) by (le))",
     "legendFormat": "P10"
    }
   ]
  },
  {
   "title": "Rate of file deletions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "sum(rate(files_deleted_from_disk_count{namespace=\"$namespace\", pod=~\"$podpattern\", status=\"success\"}[$__rate_interval])) by (status)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Pods and Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Pod Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "max_over_time(sum(kube_pod_status_phase{namespace=\"$namespace\", job=\"kube-state-metrics\", pod=~\"$podpattern\"}) by (phase)[$__rate_interval:])",
     "legendFormat": " {{phase}}"
    }
   ]
  },
  {
   "title": "Logs Volume with Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "namespace:\"$namespace\" -container:(\"wait\" OR \"init\") app_kubernetes_io_name:\"$app_kubernetes_io_name\" ~\"$query\" | count()\n\n"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 107 },
   "targets": [
    {
     "expr": "namespace:\"$namespace\" -container:(\"wait\" OR \"init\") app_kubernetes_io_name:\"$app_kubernetes_io_name\" _msg:!~ \"/health|/metrics\" ~\"$query\""
    }
   ]
  }
 ]
}