{
 "title": "AI Gateway",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "model_name", "label": "model_name", "query": { "query": "label_values(model_name)" } },
   { "name": "username", "label": "username", "query": { "query": "label_values(username)" } },
   { "name": "tenant_name", "label": "tenant_name", "query": { "query": "label_values(tenant_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Total Model Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 1, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    increase(\n      ai_gateway_requests_total{\n        model_name=~\"$model_name\",\n        username=~\"$username\",\n        tenant_name=~\"$tenant_name\"\n      }[$__range]\n    )\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Total Agent Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    increase(\n      ai_gateway_agent_requests_total{\n        model_name=~\"$model_name\",\n        username=~\"$username\",\n        tenant_name=~\"$tenant_name\"\n      }[$__range]\n    )\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Total Guardrail Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    increase(\n      ai_gateway_guardrail_requests_total{\n        model_name=~\"$model_name\",\n        username=~\"$username\",\n        tenant_name=~\"$tenant_name\"\n      }[$__range]\n    )\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Total Cost of Tokens ($)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ai_gateway_request_cost_total{model_name=~\"$model_name\", username=~\"$username\", tenant_name=~\"$tenant_name\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Average Latency (ms)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ai_gateway_request_processing_ms_sum{model_name=~\"$model_name\", username=~\"$username\", tenant_name=~\"$tenant_name\"}[$__range]))\n/\nsum(increase(ai_gateway_request_processing_ms_count{model_name=~\"$model_name\", username=~\"$username\", tenant_name=~\"$tenant_name\"}[$__range]))\n"
    }
   ]
  },
  {
   "title": "Total Input tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    increase(\n      ai_gateway_input_tokens_total{\n        model_name=~\"$model_name\",\n        username=~\"$username\",\n        tenant_name=~\"$tenant_name\"\n      }[$__range]\n    )\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Total Output tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    increase(\n      ai_gateway_output_tokens_total{\n        model_name=~\"$model_name\",\n        username=~\"$username\",\n        tenant_name=~\"$tenant_name\"\n      }[$__range]\n    )\n  )\n)\n"
    }
   ]
  },
  {
   "title": "User View",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum by (username) (\n  rate(ai_gateway_requests_total{\n    model_name=~\"$model_name\",\n    username=~\"$username\",\n    tenant_name=~\"$tenant_name\"\n  }[$__rate_interval])\n)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "sum by(username) (rate(ai_gateway_request_processing_ms_sum{model_name=~\"$model_name\", username=~\"$username\", tenant_name=~\"$tenant_name\"}[$__rate_interval])) / sum by(username) (rate(ai_gateway_request_processing_ms_count{username=~\"$username\", model_name=~\"$model_name\", tenant_name=~\"$tenant_name\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Time to First Token (ms)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 373 },
     "targets": [
      {
       "expr": "sum by(username) (rate(ai_gateway_first_token_latency_ms_sum{model_name=~\"$model_name\", username=~\"$username\", tenant_name=~\"$tenant_name\"}[$__rate_interval])) / sum by(username) (rate(ai_gateway_first_token_latency_ms_count{username=~\"$username\", model_name=~\"$model_name\", tenant_name=~\"$tenant_name\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Inter Token Latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 373 },
     "targets": [
      {
       "expr": "sum by(username) (\n  rate(ai_gateway_inter_token_latency_ms_sum{model_name=~\"$model_name\", username=~\"$username\", tenant_name=~\"$tenant_name\"}[$__rate_interval])\n)\n/\nsum by(username) (\n  rate(ai_gateway_inter_token_latency_ms_count{model_name=~\"$model_name\", username=~\"$username\", tenant_name=~\"$tenant_name\"}[$__rate_interval])\n)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Output Tokens",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 381 },
     "targets": [
      {
       "expr": "sum by(username) (\n  increase(ai_gateway_output_tokens_total{\n    model_name=~\"$model_name\",\n    username=~\"$username\",\n    tenant_name=~\"$tenant_name\"\n  }[$__interval])\n)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Input Tokens",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 381 },
     "targets": [
      {
       "expr": "sum by(username) (\n  increase(ai_gateway_input_tokens_total{\n    model_name=~\"$model_name\",\n    username=~\"$username\",\n    tenant_name=~\"$tenant_name\"\n  }[$__interval])\n)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cost of Inference ($)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 389 },
     "targets": [
      {
       "expr": "sum by(username) (\n  increase(ai_gateway_request_cost_total{\n    model_name=~\"$model_name\",\n    username=~\"$username\",\n    tenant_name=~\"$tenant_name\"\n  }[$__interval])\n)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 389 },
     "targets": [
      {
       "expr": "sum by(error_code, exception_class) (rate(ai_gateway_request_model_inference_failure_total{model_name=~\"$model_name\", username=~\"$username\", tenant_name=~\"$tenant_name\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Summary",
     "type": "table",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 397 },
     "targets": [
      { "expression": "input_time_series", "reducer": "mean", "type": "reduce" },
      { "expression": "output_time_series", "reducer": "mean", "type": "reduce" }
     ]
    }
   ]
  },
  {
   "title": "Model View",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum by (model_name) (\n  rate(ai_gateway_requests_total{\n    model_name=~\"$model_name\",\n    username=~\"$username\",\n    tenant_name=~\"$tenant_name\"\n  }[$__rate_interval])\n)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "sum by(model_name) (rate(ai_gateway_request_processing_ms_sum{model_name=~\"$model_name\", username=~\"$username\", tenant_name=~\"$tenant_name\"}[$__rate_interval])) / sum by(model_name) (rate(ai_gateway_request_processing_ms_count{username=~\"$username\", model_name=~\"$model_name\", tenant_name=~\"$tenant_name\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Time to First Token (ms)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 254 },
     "targets": [
      {
       "expr": "sum by(model_name) (rate(ai_gateway_first_token_latency_ms_sum{model_name=~\"$model_name\", username=~\"$username\", tenant_name=~\"$tenant_name\"}[$__rate_interval])) / sum by(model_name) (rate(ai_gateway_first_token_latency_ms_count{username=~\"$username\", model_name=~\"$model_name\", tenant_name=~\"$tenant_name\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Inter Token Latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 254 },
     "targets": [
      {
       "expr": "sum by(model_name) (\n  rate(ai_gateway_inter_token_latency_ms_sum{model_name=~\"$model_name\", username=~\"$username\", tenant_name=~\"$tenant_name\"}[$__rate_interval])\n)\n/\nsum by(model_name) (\n  rate(ai_gateway_inter_token_latency_ms_count{model_name=~\"$model_name\", username=~\"$username\", tenant_name=~\"$tenant_name\"}[$__rate_interval])\n)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Output Tokens",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 262 },
     "targets": [
      {
       "expr": "sum by(model_name) (\n  increase(ai_gateway_output_tokens_total{\n    model_name=~\"$model_name\",\n    username=~\"$username\",\n    tenant_name=~\"$tenant_name\"\n  }[$__interval])\n)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Input Tokens",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 262 },
     "targets": [
      {
       "expr": "sum by(model_name) (\n  increase(ai_gateway_input_tokens_total{\n    model_name=~\"$model_name\",\n    username=~\"$username\",\n    tenant_name=~\"$tenant_name\"\n  }[$__interval])\n)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cost of Inference ($)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 270 },
     "targets": [
      {
       "expr": "sum by(model_name) (\n  increase(ai_gateway_request_cost_total{\n    model_name=~\"$model_name\",\n    username=~\"$username\",\n    tenant_name=~\"$tenant_name\"\n  }[$__interval])\n)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 270 },
     "targets": [
      {
       "expr": "sum by(error_code, exception_class) (rate(ai_gateway_request_model_inference_failure_total{model_name=~\"$model_name\", username=~\"$username\", tenant_name=~\"$tenant_name\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Summary",
     "type": "table",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 278 },
     "targets": [
      { "expression": "input_time_series", "reducer": "mean", "type": "reduce" },
      { "expression": "output_time_series", "reducer": "mean", "type": "reduce" }
     ]
    }
   ]
  },
  {
   "title": "Config View",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate Limit Rules Applied",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum by (ruleId) (\n  rate(ai_gateway_rate_limit_applied_total{\n    model_name=~\"$model_name\",\n    username=~\"$username\",\n    tenant_name=~\"$tenant_name\"\n  }[$__rate_interval])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate Limit Rules Nominated",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "sum by (ruleId) (\n  rate(ai_gateway_rate_limit_nominated_total{\n    model_name=~\"$model_name\",\n    username=~\"$username\",\n    tenant_name=~\"$tenant_name\"\n  }[$__rate_interval])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Budget Rules Applied",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 223 },
     "targets": [
      {
       "expr": "sum by (ruleId) (\n  rate(ai_gateway_budget_applied_total{\n    model_name=~\"$model_name\",\n    username=~\"$username\",\n    tenant_name=~\"$tenant_name\"\n  }[$__rate_interval])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Budget Limit Rules Nominated",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 223 },
     "targets": [
      {
       "expr": "sum by (ruleId) (\n  rate(ai_gateway_budget_nominated_total{\n    model_name=~\"$model_name\",\n    username=~\"$username\",\n    tenant_name=~\"$tenant_name\"\n  }[$__rate_interval])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Budget Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 231 },
     "targets": [
      {
       "expr": "max by (ruleId) (\n  ai_gateway_budget_usage\n)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Routing Config",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 231 },
     "targets": [
      {
       "expr": "sum by(ruleId) (\n  increase(ai_gateway_load_balanced_requests_total{\n    model_name=~\"$model_name\",\n    username=~\"$username\",\n    tenant_name=~\"$tenant_name\"\n  }[$__interval])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Guardrail Requests Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 239 },
     "targets": [
      {
       "expr": "sum by (guardrail_fqn, result) (\n  rate(ai_gateway_guardrail_requests_total{\n    model_name=~\"$model_name\",\n    username=~\"$username\",\n    tenant_name=~\"$tenant_name\"\n  }[$__rate_interval])\n)\n"
      }
     ]
    },
    {
     "title": "Guardrail Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 239 },
     "targets": [
      {
       "expr": "sum by (guardrail_fqn) (\n  rate(ai_gateway_guardrail_execution_latency_ms_sum{\n    model_name=~\"$model_name\",\n    username=~\"$username\",\n    tenant_name=~\"$tenant_name\"\n  }[$__rate_interval])\n)\n/\nsum by (guardrail_fqn) (\n  rate(ai_gateway_guardrail_execution_latency_ms_count{\n    model_name=~\"$model_name\",\n    username=~\"$username\",\n    tenant_name=~\"$tenant_name\"\n  }[$__rate_interval])\n)\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "MCP Invocation Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Agent Request Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(model_name) (\n  rate(ai_gateway_agent_request_duration_ms_sum{\n    model_name=~\"$model_name\", username=~\"$username\", tenant_name=~\"$tenant_name\"\n  }[$__rate_interval])\n)\n/\nsum by(model_name) (\n  rate(ai_gateway_agent_request_duration_ms_count{\n    model_name=~\"$model_name\", username=~\"$username\", tenant_name=~\"$tenant_name\"\n  }[$__rate_interval])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MCP Connection Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(tenant_name) (\n  rate(ai_gateway_agent_mcp_connect_latency_ms_sum{username=~\"$username\", tenant_name=~\"$tenant_name\"\n  }[$__rate_interval])\n)\n/\nsum by(tenant_name) (\n  rate(ai_gateway_agent_mcp_connect_latency_ms_count{\n    username=~\"$username\", tenant_name=~\"$tenant_name\"\n  }[$__rate_interval])\n)"
    }
   ]
  },
  {
   "title": "Tool Call Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(tool_name) (\n  rate(ai_gateway_agent_tool_latency_ms_sum{username=~\"$username\", tenant_name=~\"$tenant_name\"\n  }[$__rate_interval])\n)\n/\nsum by(tool_name) (\n  rate(ai_gateway_agent_tool_latency_ms_count{username=~\"$username\", tenant_name=~\"$tenant_name\"\n  }[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "Tool Calls Average Latency (ms)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (tool_name) (rate(ai_gateway_agent_tool_latency_ms_sum{tool_name!=\"\"}[$__rate_interval]))\n/\nsum by (tool_name) (rate(ai_gateway_agent_tool_latency_ms_count{tool_name!=\"\"}[$__rate_interval]))\n",
     "legendFormat": "{{tool_name}}"
    }
   ]
  },
  {
   "title": "Tool Calls per Agent Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(model_name) (\n  rate(ai_gateway_agent_request_tool_calls_sum{\n    model_name=~\"$model_name\", username=~\"$username\", tenant_name=~\"$tenant_name\"\n  }[$__rate_interval])\n)\n/\nsum by(model_name) (\n  rate(ai_gateway_agent_request_tool_calls_count{\n    model_name=~\"$model_name\", username=~\"$username\", tenant_name=~\"$tenant_name\"\n  }[$__rate_interval])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tool Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "round(\n  sum by (tool_name, integration_fqn) (\n    increase(ai_gateway_agent_tool_calls_total{\n      username=~\"$username\",\n      tenant_name=~\"$tenant_name\"\n    }[$__range])\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Iteration Limit Reached",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(model_name) (\n  increase(ai_gateway_agent_request_iteration_limit_reached_total{\n    model_name=~\"$model_name\", username=~\"$username\", tenant_name=~\"$tenant_name\"\n  }[$__interval])\n)"
    }
   ]
  },
  { "title": "Span Export Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Spans Accepted (rate)",
   "type": "timeseries",
   "description": "Rate of ai_gateway_spans_accepted_total — spans that passed the gateway's span processor checks and were handed to the exporter. Top of the export funnel; baseline for what should reach the collector.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(ai_gateway_spans_accepted_total{tenant_name=~\"$tenant_name\"}[5m]))",
     "legendFormat": "accepted"
    }
   ]
  },
  {
   "title": "Spans Exported by Outcome (rate)",
   "type": "timeseries",
   "description": "Rate of ai_gateway_spans_exported_total split success vs failed. One increment per export batch on its terminal outcome (retries are not double-counted). 'success' should track 'accepted'; any 'failed' is telemetry lost at the collector hop.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (outcome) (rate(ai_gateway_spans_exported_total{tenant_name=~\"$tenant_name\"}[5m]))",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Span Drops (rate)",
   "type": "timeseries",
   "description": "Rate of ai_gateway_span_drops_total — spans dropped by the gateway span processor BEFORE export (should_trace off, or missing created_by_subject). Distinct from export failures: these never entered the exporter. See 'Drops by Reason' for the breakdown.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(ai_gateway_span_drops_total{tenant_name=~\"$tenant_name\"}[5m]))",
     "legendFormat": "drops"
    }
   ]
  },
  {
   "title": "Successful Exports by Tenant (rate)",
   "type": "timeseries",
   "description": "rate(ai_gateway_spans_exported_total{outcome=\"success\"}) grouped by tenant_name — spans that actually reached the collector per tenant. Compare against 'Accepted by Tenant' to spot per-tenant loss.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (tenant_name) (rate(ai_gateway_spans_exported_total{tenant_name=~\"$tenant_name\", outcome=\"success\"}[5m]))",
     "legendFormat": "{{tenant_name}}"
    }
   ]
  },
  {
   "title": "Failed Exports by Tenant & Reason (rate)",
   "type": "timeseries",
   "description": "rate(ai_gateway_spans_exported_total{outcome=\"failed\"}) grouped by tenant_name AND reason. Reason buckets: timeout / connection_refused / http_4xx / http_5xx / unknown. A tenant spiking here is losing telemetry; the reason says where to look.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (tenant_name, reason) (rate(ai_gateway_spans_exported_total{tenant_name=~\"$tenant_name\", outcome=\"failed\"}[5m]))",
     "legendFormat": "{{tenant_name}} · {{reason}}"
    }
   ]
  },
  {
   "title": "Accepted by Tenant (rate)",
   "type": "timeseries",
   "description": "rate(ai_gateway_spans_accepted_total) grouped by tenant_name — per-tenant baseline entering the export path. High accepted but low successful export = downstream loss for that tenant.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (tenant_name) (rate(ai_gateway_spans_accepted_total{tenant_name=~\"$tenant_name\"}[5m]))",
     "legendFormat": "{{tenant_name}}"
    }
   ]
  },
  {
   "title": "Drops by Reason (rate)",
   "type": "timeseries",
   "description": "rate(ai_gateway_span_drops_total) grouped by reason. should_trace_false = tracing intentionally off (usually expected). missing_created_by_subject_child = request context not propagated. missing_created_by_subject_root = 'should never happen' bug — investigate any non-zero.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (reason) (rate(ai_gateway_span_drops_total{tenant_name=~\"$tenant_name\"}[5m]))",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Failed Exports by Tenant & Reason — total over selected range",
   "type": "table",
   "description": "Total count (not a rate) of failed exported spans over the dashboard's time range, per tenant × reason, via increase(...[$__range]). Tracks the time picker — widen the range to include when failures occurred. NOTE: increase() extrapolates to range edges, so values are estimates and may be fractional. Empty means the counter didn't grow in the selected window (failures may be older).",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (tenant_name, reason) (increase(ai_gateway_spans_exported_total{tenant_name=~\"$tenant_name\", outcome=\"failed\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}