{
 "title": "Prometheus",
 "tags": [
  "truefoundry",
  "prometheus"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Max active time series count in last 24h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(prometheus_tsdb_head_series{job=\"prometheus\"}[1d])"
    }
   ]
  },
  {
   "title": "Memory usage (GiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "round((sum(container_memory_working_set_bytes{namespace=\"prometheus\",container!=\"POD\",container!=\"\", pod=\"prometheus-prometheus-kube-prometheus-prometheus-0\", job=\"kubelet\"}))/1024/1024/1024, 0.001)",
     "legendFormat": "Usage"
    },
    {
     "expr": "round(sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"memory\",namespace=\"prometheus\",container!=\"POD\",container!=\"\", pod=\"prometheus-prometheus-kube-prometheus-prometheus-0\"})/1024/1024/1024, 0.001)",
     "legendFormat": "Requested"
    },
    {
     "expr": "round(sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"memory\",namespace=\"prometheus\",container!=\"POD\",container!=\"\", pod=\"prometheus-prometheus-kube-prometheus-prometheus-0\",}/1024/1024/1024), 0.001)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Active Time Series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(max_over_time(prometheus_tsdb_head_series{job=\"prometheus\"}[$__interval]))",
     "legendFormat": "Active Time Series"
    }
   ]
  },
  {
   "title": "Total number of samples loaded by queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(prometheus_engine_query_samples_total{pod=\"prometheus-prometheus-kube-prometheus-prometheus-0\",job=\"prometheus\"}[$__rate_interval])",
     "legendFormat": "Total number of samples loaded by queries"
    }
   ]
  },
  {
   "title": "Scrape - new time series added ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (job, container, namespace) (scrape_series_added)"
    }
   ]
  },
  {
   "title": "Scrape - samples post re-labelling ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (job, container, namespace) (scrape_samples_post_metric_relabeling)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Samples ingested per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_head_samples_appended_total{job=\"prometheus\", pod=\"prometheus-prometheus-kube-prometheus-prometheus-0\"}[$__rate_interval]))",
     "legendFormat": "Samples ingested per second"
    },
    {}
   ]
  },
  {
   "title": "Instant/Range HTTP queries response time (sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(prometheus_http_request_duration_seconds_bucket{job=\"prometheus\", handler=~\"/api/v1/query|/api/v1/query_range\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(prometheus_http_request_duration_seconds_bucket{job=\"prometheus\", handler=~\"/api/v1/query|/api/v1/query_range\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(prometheus_http_request_duration_seconds_bucket{job=\"prometheus\", handler=~\"/api/v1/query|/api/v1/query_range\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "HTTP status code distribution of Range/Instant HTTP queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(prometheus_http_requests_total{job=\"prometheus\", handler=~\"/api/v1/query|/api/v1/query_range\"}[$__rate_interval])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "round(sum(rate(container_cpu_usage_seconds_total{namespace=\"prometheus\",container!=\"POD\",container!=\"\", pod=\"prometheus-prometheus-kube-prometheus-prometheus-0\", job=\"kubelet\"}[$__rate_interval])), 0.001)",
     "legendFormat": "Usage"
    },
    {
     "expr": "round(sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"cpu\",namespace=\"prometheus\",container!=\"POD\",container!=\"\", pod=\"prometheus-prometheus-kube-prometheus-prometheus-0\"}), 0.001)",
     "legendFormat": "Requested"
    },
    {
     "expr": "round(sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"cpu\",namespace=\"prometheus\",container!=\"POD\",container!=\"\", pod=\"prometheus-prometheus-kube-prometheus-prometheus-0\",}), 0.001)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "HTTP request per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(prometheus_http_requests_total{job=\"prometheus\", handler!~\"/api/v1/query|/api/v1/query_range\"}[$__rate_interval]))",
     "legendFormat": "Other HTTP requests"
    },
    {
     "expr": "sum(rate(prometheus_http_requests_total{job=\"prometheus\", handler=~\"/api/v1/query|/api/v1/query_range\"}[$__rate_interval]))",
     "legendFormat": "Range/Instant Metrics query"
    }
   ]
  },
  {
   "title": "Bytes per sample in last 24 hours",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  rate(prometheus_tsdb_compaction_chunk_size_bytes_sum[24h])\n/\n  rate(prometheus_tsdb_compaction_chunk_samples_sum[24h])"
    }
   ]
  },
  {
   "title": "Total number of queries executing or waiting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "prometheus_engine_queries{pod=\"prometheus-prometheus-kube-prometheus-prometheus-0\",job=\"prometheus\"}",
     "legendFormat": "Total number of queries executing or waiting"
    },
    {
     "expr": "prometheus_engine_queries_concurrent_max{pod=\"prometheus-prometheus-kube-prometheus-prometheus-0\",job=\"prometheus\"}",
     "legendFormat": "max allowed concurrent queries"
    }
   ]
  },
  {
   "title": "Million samples ingested in last 24h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_tsdb_head_samples_appended_total{job=\"prometheus\", pod=\"prometheus-prometheus-kube-prometheus-prometheus-0\"}[24h])) / 1e6"
    }
   ]
  },
  {
   "title": "Disk usage (GiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"prometheus-prometheus-kube-prometheus-prometheus-db-prometheus-prometheus-kube-prometheus-prometheus-0\", namespace=\"prometheus\", job=\"kubelet\"}) / 1024 / 1024 / 1024",
     "legendFormat": "Disk usage (GiB)"
    }
   ]
  }
 ]
}