{
 "title": "Argo Workflows",
 "description": "Metrics from Argo Workflows compatible with multi-Prometheus origins like Thanos.",
 "tags": [ "argo" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "dc",
    "label": "Kubernetes Cluster",
    "query": {
     "query": "label_values(argo_workflows_total_count,prometheus)"
    }
   },
   {
    "name": "ns",
    "label": "WF Controller Namespace",
    "query": {
     "query": "label_values(argo_workflows_total_count{prometheus=~\"^$dc$\"},namespace)"
    }
   },
   { "name": "ts", "label": "Time Range", "query": "12h,1d,7d,14d,30d,90d" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Workflows by Phase in the last $ts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (phase) (increase(argo_workflows_total_count{prometheus=~\"^$dc$\",namespace=~\"$ns\"}[$ts]))",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  { "title": "Count of Workflows by status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Workflow Status  ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(\n  sum by (prometheus, namespace, phase) (\n    increase(argo_workflows_total_count{phase!~\"Failed\"}[1m])\n  ) > 0\n)\nunless on (prometheus, namespace, phase)\n(\n  sum by (prometheus, namespace, phase) (\n    increase(argo_workflows_total_count{phase!~\"Failed\"}[1m] offset 1h)\n  ) > 0\n)",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{phase}}"
    }
   ]
  },
  {
   "title": "Workflow Errors/Failures ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(\n  sum by (prometheus, namespace, phase) (\n    increase(argo_workflows_total_count{phase=\"Failed\"}[1m])\n  ) > 0\n)\nunless on (prometheus, namespace, phase)\n(\n  sum by (prometheus, namespace, phase) (\n    increase(argo_workflows_total_count{phase=\"Failed\"}[1m] offset 1h)\n  ) > 0\n)",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{phase}}"
    }
   ]
  },
  { "title": "Workflow Controler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Workflow operation duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(argo_workflows_operation_duration_seconds_bucket{prometheus=~\"^$dc$\",namespace=~\"^$ns$\"}[5m])) by (le,prometheus,namespace)) ",
     "legendFormat": "{{prometheus}} : {{namespace}} : 95th "
    }
   ]
  },
  {
   "title": "Workflow queue adds ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (prometheus, namespace, queue_name) (increase(argo_workflows_queue_adds_count{prometheus=~\"^$dc$\",namespace=~\"$ns\"}[2m]))",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{queue_name}}"
    }
   ]
  },
  {
   "title": "Depth of the queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (prometheus, namespace, queue_name) (argo_workflows_queue_depth_gauge{prometheus=~\"^$dc$\",namespace=~\"$ns\"})",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{queue_name}}"
    }
   ]
  },
  {
   "title": "Time objects spend waiting in the queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "  sum by (prometheus, namespace, queue_name) (rate(argo_workflows_queue_latency_sum{}[1m]))\n/\n  sum by (prometheus, namespace, queue_name) (rate(argo_workflows_queue_latency_count{}[1m]))",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{queue_name}}"
    }
   ]
  },
  {
   "title": "Log messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (prometheus, namespace, level) (rate(argo_workflows_log_messages{namespace=~\"$ns\",prometheus=~\"^$dc$\"}[1m]))",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{level}}"
    }
   ]
  },
  { "title": "WorkflowTemplates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "WorkflowTemplates Succeeded over the last $ts",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (increase(argo_workflows_workflowtemplate_triggered_total{prometheus=~\"^$dc$\",namespace=~\"$ns\",phase=\"Succeeded\"}[$ts])) > 0)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "WorkflowTemplates Failed/Errored over the last $ts",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (increase(argo_workflows_workflowtemplate_triggered_total{prometheus=~\"^$dc$\",namespace=~\"$ns\",phase=~\"Failed|Error\"}[$ts])) > 0 )",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Workflow Template Runtime (95th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (rate(argo_workflows_workflowtemplate_runtime_bucket{prometheus=~\"^$dc$\",namespace=~\"^$ns$\"}[5m])) by (le,name,prometheus,namespace)) ",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{name}} : 95th "
    }
   ]
  },
  {
   "title": "ClusterWorkflowTemplates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "ClusterWorkflowTemplates Succeeded over the last $ts",
     "type": "stat",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 77 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (name) (increase(argo_workflows_clusterworkflowtemplate_triggered_total{phase=\"Succeeded\"}[$ts])))",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "ClusterWorkflowTemplates Failed/Errored over the last $ts",
     "type": "stat",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 83 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (name) (increase(argo_workflows_clusterworkflowtemplate_triggered_total{prometheus=~\"^$dc$\",namespace=~\"$ns\",phase=~\"Failed|Error\"}[$ts])))",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "ClusterWorkflowTemplates Status  ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(sum by (prometheus, namespace, phase, name) (argo_workflows_clusterworkflowtemplate_triggered_total{prometheus=~\"^$dc$\",namespace=~\"$ns\"})[1m:1m]) > 0 unless\nincrease(sum by (prometheus, namespace, phase, name) (argo_workflows_clusterworkflowtemplate_triggered_total{prometheus=~\"^$dc$\",namespace=~\"$ns\"})[1m:1m] offset 1d)\nor\nincrease(sum by (prometheus, namespace, phase, name) (argo_workflows_clusterworkflowtemplate_triggered_total{prometheus=~\"^$dc$\",namespace=~\"$ns\"})[1m:1m]) > 0 -\nincrease(sum by (prometheus, namespace, phase, name) (argo_workflows_clusterworkflowtemplate_triggered_total{prometheus=~\"^$dc$\",namespace=~\"$ns\"})[1m:1m] offset 1d)",
       "legendFormat": "{{prometheus}} : {{namespace}} : {{name}} : {{phase}}"
      }
     ]
    }
   ]
  },
  { "title": "CronWorkflows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "CronWorkflows Triggered over the last $ts",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (increase(argo_workflows_cronworkflows_triggered_total{prometheus=~\"^$dc$\",namespace=~\"$ns\"}[12h])) > 0 )",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  { "title": "Workflow Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Workflow Pods by State",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (prometheus, namespace, phase) (argo_workflows_pods_gauge{prometheus=~\"^$dc$\",namespace=~\"$ns\"})",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{phase}}"
    },
    {
     "expr": "(\n  sum by (prometheus, namespace) (\n    max_over_time(argo_workflows_pod_pending_count{prometheus=~\"^$dc$\", namespace=~\"$ns\"}[1m])\n  ) > 0\n)\nunless on (prometheus, namespace)\n(\n  sum by (prometheus, namespace) (\n    max_over_time(argo_workflows_pod_pending_count{prometheus=~\"^$dc$\", namespace=~\"$ns\"}[1m] offset 1d)\n  ) > 0\n)",
     "legendFormat": "{{prometheus}} : {{namespace}} : Pending"
    }
   ]
  },
  {
   "title": "Top 5 Pending Pods by reason in the last $ts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 95 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n  5,\n  clamp_min(\n    sum by (reason, prometheus, namespace) (\n      max_over_time(argo_workflows_pod_pending_count{prometheus=~\"^$dc$\", namespace=~\"$ns\"}[$ts])\n    )\n  -\n    sum by (reason, prometheus, namespace) (\n      max_over_time(argo_workflows_pod_pending_count{prometheus=~\"^$dc$\", namespace=~\"$ns\"}[$ts] offset 1d)\n    ),\n    0\n  )\n)",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{reason}}"
    }
   ]
  }
 ]
}