{
 "title": "ArgoCD",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Applications",
   "type": "stat",
   "description": "Shows the total number of Argo CD Applications discovered in the cluster to indicate overall footprint.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(argocd_app_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Application Sync Status",
   "type": "stat",
   "description": "Total number of syncs, broken down by their phase",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_sync_total) by (phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Health Status",
   "type": "gauge",
   "description": "Shows count of apps by health state (Healthy, Degraded, Missing) to detect widespread problems.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (health_status) (argocd_app_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Sync Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(argocd_app_info{operation!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync Stats",
   "type": "stat",
   "description": "percentage of apps in Synced state vs total",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{sync_status=\"Synced\"}) / sum(argocd_app_info{}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Controller Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Reconciliation Activity",
   "type": "timeseries",
   "description": "controller reconcile operations per second to monitor controller workload.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(argocd_app_reconcile_count{}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconciliation Performance",
   "type": "timeseries",
   "description": "p95 reconcile duration (seconds) to track controller performance regressions.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(argocd_app_reconcile_bucket{}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "K8s API Activity",
   "type": "timeseries",
   "description": "API client requests/sec by verb/resource, revealing potential API bottlenecks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by (verb,resource) (rate(controller_clientset_k8s_request_total{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workqueue Depth",
   "type": "timeseries",
   "description": "Queue size of controller workqueues to catch backlogs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum by (name) (workqueue_depth{})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Resource Object Counts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(argocd_cluster_api_resource_objects{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Resources Count",
   "type": "stat",
   "description": "Number of API resource types seen by the controller to track CRD growth.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (argocd_cluster_api_resources{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Events Count",
   "type": "timeseries",
   "description": "Kubernetes event emission rate.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "rate(argocd_cluster_events_total{}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Repo Server Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Git Requests (ls-remote)",
   "type": "timeseries",
   "description": "Shows ls-remote calls/sec to Git remotes (manifest discovery), high values may hit rate limits.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "rate(argocd_git_request_total{request_type=\"ls-remote\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Git Requests (Checkout)",
   "type": "timeseries",
   "description": "Shows checkout operations/sec (render workload), useful to size repo server.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "rate(argocd_git_request_total{request_type!=\"checkout\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Git Fetch Perforamance",
   "type": "timeseries",
   "description": "p95 duration of git fetch to catch SCM latency/regressions.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(argocd_git_request_duration_seconds_bucket{request_type=\"fetch\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "collapsed": true,
   "panels": [
    {
     "title": "Argocd Controller",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 111 },
     "targets": [
      {
       "expr": "app_kubernetes_io_name: \"argocd-application-controller\""
      }
     ]
    },
    {
     "title": "Argocd Server",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 119 },
     "targets": [
      {
       "expr": "app_kubernetes_io_instance: \"argocd\" AND app_kubernetes_io_name: \"argocd-server\""
      }
     ]
    },
    {
     "title": "Argocd Repo Server",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 127 },
     "targets": [
      {
       "expr": "app_kubernetes_io_instance: \"argocd\" AND app_kubernetes_io_name: \"argocd-repo-server\""
      }
     ]
    }
   ]
  }
 ]
}