{
 "title": "AWS EBS metrics",
 "description": "You can monitor the performance EBS - AWS",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(cluster_name)" } },
   {
    "name": "volume",
    "query": {
     "query": "label_values(aws_ebs_volume_idle_time_average{cluster_name=\"$cluster\"}, volume_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Performance - EBS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Storage Latency (Seconds per Operation)",
   "type": "timeseries",
   "description": "The result of this calculation would give you the average time spent per operation, effectively measuring latency. If you see peaks or fluctuations in this value over time, it could indicate potential issues causing latency in your EBS storage.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "\n(\n  aws_ebs_volume_total_read_time_average{cluster_name=~\"$cluster\", volume_id=~\"$volume\"}\n  + aws_ebs_volume_total_write_time_average{cluster_name=~\"$cluster\", volume_id=~\"$volume\"}\n)\n/\n(\n  aws_ebs_volume_read_ops_average{cluster_name=~\"$cluster\", volume_id=~\"$volume\"}\n  + aws_ebs_volume_write_ops_average{cluster_name=~\"$cluster\", volume_id=~\"$volume\"}\n)\n",
     "legendFormat": "Volume Id: {{volume_id}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "\n(\n  aws_ebs_volume_read_ops_average{cluster_name=~\"$cluster\", volume_id=~\"$volume\"}\n  + aws_ebs_volume_write_ops_average{cluster_name=~\"$cluster\", volume_id=~\"$volume\"}\n)\n/\n60",
     "legendFormat": "Volume Id: {{volume_id}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(\n  aws_ebs_volume_read_bytes_average{cluster_name=~\"$cluster\", volume_id=~\"$volume\"}\n  + aws_ebs_volume_write_bytes_average{cluster_name=~\"$cluster\", volume_id=~\"$volume\"}\n)\n/\n60",
     "legendFormat": "Volume Id: {{volume_id}}"
    }
   ]
  },
  { "title": "Commond - EBS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Volume Read Ops",
   "type": "timeseries",
   "description": "This metric gives you the total number of read operations from an EBS volume in a specified period of time. Sudden changes could indicate a change in the behavior of the applications using the volume",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "aws_ebs_volume_read_ops_average{cluster_name=~\"$cluster\", volume_id=~\"$volume\"}",
     "legendFormat": "Volume ID: {{ volume_id }}"
    }
   ]
  },
  {
   "title": "Volume Write Ops",
   "type": "timeseries",
   "description": "This metric gives you the total number of read operations from an EBS volume in a specified period of time. Sudden changes could indicate a change in the behavior of the applications using the volume",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "aws_ebs_volume_write_ops_average{cluster_name=~\"$cluster\", volume_id=~\"$volume\"}",
     "legendFormat": "Volume ID: {{ volume_id }}"
    }
   ]
  },
  {
   "title": "Volume Read Bytes",
   "type": "timeseries",
   "description": "These metrics represent the total bytes read or written from an EBS volume. These metrics help you understand the amount of data being read or written over time. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aws_ebs_volume_read_bytes_average{cluster_name=~\"$cluster\", volume_id=~\"$volume\"}",
     "legendFormat": "Volume ID: {{ volume_id }}"
    }
   ]
  },
  {
   "title": "Volume Write Bytes",
   "type": "timeseries",
   "description": "These metrics represent the total bytes read or written from an EBS volume. These metrics help you understand the amount of data being read or written over time. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aws_ebs_volume_write_bytes_average{cluster_name=~\"$cluster\", volume_id=~\"$volume\"}",
     "legendFormat": "Volume ID: {{ volume_id }}"
    }
   ]
  },
  {
   "title": "Volume Total Read Time",
   "type": "timeseries",
   "description": "These metrics give you the total time taken for read and write operations. If these values are increasing, it could indicate a performance issue. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "aws_ebs_volume_total_read_time_average{cluster_name=~\"$cluster\", volume_id=~\"$volume\"}",
     "legendFormat": "Volume ID: {{ volume_id }}"
    }
   ]
  },
  {
   "title": "Volume Total Write Time",
   "type": "timeseries",
   "description": "These metrics give you the total time taken for read and write operations. If these values are increasing, it could indicate a performance issue. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "aws_ebs_volume_total_write_time_average{cluster_name=~\"$cluster\", volume_id=~\"$volume\"}",
     "legendFormat": "Volume ID: {{ volume_id }}"
    }
   ]
  },
  {
   "title": "Volume Queue Length",
   "type": "timeseries",
   "description": "This is an important metric that provides the number of read and write operation requests waiting to be completed. A high queue length might indicate that your volume's performance is being maxed out. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aws_ebs_volume_queue_length_average{cluster_name=~\"$cluster\", volume_id=~\"$volume\"}",
     "legendFormat": "Volume ID: {{ volume_id }}"
    }
   ]
  },
  {
   "title": "VolumeIdleTime",
   "type": "timeseries",
   "description": "This metric gives you the total time that the volume was idle. This can help you identify volumes that are being under-utilized. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "aws_ebs_volume_idle_time_average{cluster_name=~\"$cluster\", volume_id=~\"$volume\"}",
     "legendFormat": "Volume ID: {{ volume_id }}"
    }
   ]
  },
  {
   "title": "Samba Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {}
     ]
    }
   ]
  }
 ]
}