{
 "title": "Elasti",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Running Pods",
   "type": "stat",
   "description": "number of running pods",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\", namespace=\"elasti\", pod=~\".*elasti-operator.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container restarts (24h)",
   "type": "timeseries",
   "description": "restart increments over 24h",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"elasti\", pod=~\".*elasti-operator.*\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage (cores) per pod/container",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (container) (rate(container_cpu_usage_seconds_total{namespace=\"elasti\", pod=~\".*elasti-operator.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "description": "CPU usage percentage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "100 *\nsum by (namespace, pod, container) (\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"elasti\",\n    pod=~\".*elasti-operator.*\",\n    container!=\"\"\n  }[5m])\n)\n/\nclamp_min(\n  sum by (namespace, pod, container) (\n    kube_pod_container_resource_requests{\n      namespace=\"elasti\",\n      pod=~\".*elasti-operator.*\",\n      container!=\"\",\n      resource=\"cpu\"\n    }\n  ),\n  0.001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\", namespace=\"elasti\", pod=~\".*elasti-operator.*\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "timeseries",
   "description": "Memory usage percentage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "100 *\nsum by (namespace, pod) (\n  container_memory_working_set_bytes{\n    namespace=\"elasti\",\n    pod=~\".*elasti-operator.*\",\n    container!=\"\", container!=\"POD\"\n  }\n)\n/\nclamp_min(\n  sum by (namespace, pod) (\n    kube_pod_container_resource_limits{\n      namespace=\"elasti\", \n      pod=~\".*elasti-operator.*\",\n      resource=\"memory\"\n    }\n  ),\n  1\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}