{
 "title": "Nvidia GPU",
 "description": "GPU dashboard for nvidia metrics ",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(DCGM_FI_PROF_GR_ENGINE_ACTIVE, instance)"
    }
   },
   {
    "name": "gpu",
    "query": {
     "query": "label_values(DCGM_FI_PROF_GR_ENGINE_ACTIVE, gpu)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total GPU Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  kube_node_labels{\n    label_karpenter_sh_nodepool=\"gpu-nodepool\",\n    job=\"kube-state-metrics\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Cluster GPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", service=\"prometheus-kube-state-metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Cluster GPU Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_FB_USED + DCGM_FI_DEV_FB_FREE + DCGM_FI_DEV_FB_RESERVED)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_PROF_GR_ENGINE_ACTIVE) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum(DCGM_FI_DEV_FB_USED)\n/\nsum(DCGM_FI_DEV_FB_USED + DCGM_FI_DEV_FB_FREE + DCGM_FI_DEV_FB_RESERVED)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spot Node Percentage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(kube_node_labels{label_karpenter_sh_capacity_type=\"spot\", label_nvidia_com_gpu_present=\"true\"}) /\n  count(kube_node_labels{label_nvidia_com_gpu_present=\"true\"})\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GPU Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "GPUs Deployed",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "count by (Hostname, modelName) (DCGM_FI_PROF_GR_ENGINE_ACTIVE)",
     "legendFormat": "{{ GPU }}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "AVG(DCGM_FI_DEV_GPU_TEMP{instance=~\"$instance\", gpu=~\"$gpu\"}) BY (instance, gpu)",
     "legendFormat": "{{instance}}-gpu{{gpu}}"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "AVG(DCGM_FI_DEV_POWER_USAGE{instance=~\"$instance\", gpu=~\"$gpu\"}) BY (instance, gpu)",
     "legendFormat": "{{instance}}-gpu{{gpu}}"
    }
   ]
  },
  {
   "title": "PCIe Tx/Rx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "-DCGM_FI_PROF_PCIE_TX_BYTES{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "{{instance}}-gpu{{gpu}}-Tx"
    },
    {
     "expr": "DCGM_FI_PROF_PCIE_RX_BYTES{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "{{instance}}-gpu{{gpu}}-Rx"
    }
   ]
  },
  {
   "title": "Cycles Memory Interface",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "AVG(DCGM_FI_PROF_DRAM_ACTIVE{instance=~\"$instance\", gpu=~\"$gpu\"}) BY (instance, gpu)",
     "legendFormat": "{{instance}}-gpu{{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Operator Resource Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "description": "number of running pods",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\", namespace=\"tfy-gpu-operator\", pod=~\"gpu-operator.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OOM Kills (24h)",
   "type": "timeseries",
   "description": "restart increments over 24h",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "increase(container_oom_events_total{namespace=\"tfy-gpu-operator\", pod=~\"gpu-operator.*\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage (cores) per pod/container",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by (container) (rate(container_cpu_usage_seconds_total{namespace=\"tfy-gpu-operator\", pod=~\"gpu-operator.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "description": "CPU usage percentage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "100 *\nsum by (namespace, pod, container) (\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"tfy-gpu-operator\",\n    pod=~\"gpu-operator.*\",\n    container!=\"\"\n  }[5m])\n)\n/\nclamp_min(\n  sum by (namespace, pod, container) (\n    kube_pod_container_resource_requests{\n      namespace=\"tfy-gpu-operator\",\n      pod=~\"gpu-operator.*\",\n      container!=\"\",\n      resource=\"cpu\"\n    }\n  ),\n  0.001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\", namespace=\"tfy-gpu-operator\", pod=~\"gpu-operator.*\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "timeseries",
   "description": "Memory usage percentage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "100 *\nsum by (namespace, pod) (\n  container_memory_working_set_bytes{\n    namespace=\"tfy-gpu-operator\",\n    pod=~\"gpu-operator.*\",\n    container!=\"\", container!=\"POD\"\n  }\n)\n/\nclamp_min(\n  sum by (namespace, pod) (\n    kube_pod_container_resource_limits{\n      namespace=\"tfy-gpu-operator\",\n      pod=~\"gpu-operator.*\",\n      resource=\"memory\"\n    }\n  ),\n  1\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}