{
 "title": "Kubernetes / Autoscaling / Karpenter / Activity",
 "description": "A dashboard that monitors Karpenter and focuses on Karpenter deletion/creation activity. It is created using the [kubernetes-autoscaling-mixin](https://github.com/adinhodovic/kubernetes-autoscaling-mixin).",
 "tags": [
  "kubernetes",
  "autoscaling",
  "kubernetes-autoscaling-mixin",
  "karpenter"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(karpenter_nodes_allocatable{}, job)"
   },
   {
    "name": "nodepool",
    "label": "Node Pool",
    "query": "label_values(karpenter_nodepools_allowed_disruptions{job=~\"$job\"}, nodepool)"
   }
  ]
 },
 "panels": [
  { "title": "Node Pool Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes Created by Node Pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    increase(\n      karpenter_nodes_created_total{\n        job=~\"$job\",\n        nodepool=~\"$nodepool\"\n      }[$__rate_interval]\n    )\n  ) by (nodepool)\n)\n",
     "legendFormat": "{{ nodepool }}"
    }
   ]
  },
  {
   "title": "Nodes Terminated by Node Pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    increase(\n      karpenter_nodes_terminated_total{\n        job=~\"$job\",\n        nodepool=~\"$nodepool\"\n      }[$__rate_interval]\n    )\n  ) by (nodepool)\n)\n",
     "legendFormat": "{{ nodepool }}"
    }
   ]
  },
  {
   "title": "Node Disruption Decisions by Reason and Decision",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    increase(\n      karpenter_voluntary_disruption_decisions_total{\n        job=~\"$job\",\n      }[$__rate_interval]\n    )\n  ) by (decision, reason)\n)\n",
     "legendFormat": "{{ decision }} - {{ reason }}"
    }
   ]
  },
  {
   "title": "Nodes Eligible for Disruption by Reason",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    increase(\n      karpenter_voluntary_disruption_eligible_nodes{\n        job=~\"$job\",\n      }[$__rate_interval]\n    )\n  ) by (reason)\n)\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Nodes Disrupted by Node Pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    increase(\n      karpenter_nodeclaims_disrupted_total{\n        job=~\"$job\",\n        nodepool=~\"$nodepool\"\n      }[$__rate_interval]\n    )\n  ) by (nodepool, capacity_type, reason)\n)\n",
     "legendFormat": "{{ nodepool }} - {{ capacity_type }} - {{ reason }}"
    }
   ]
  },
  { "title": "Pod Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Pods by Phase",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    karpenter_pods_state{\n      job=~\"$job\"\n    }\n  ) by (phase)\n)\n",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Pods Startup Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(\n  karpenter_pods_startup_duration_seconds{\n    job=~\"$job\",\n    quantile=\"0.5\"\n  }\n)\n",
     "legendFormat": "P50"
    },
    {
     "expr": "max(\n  karpenter_pods_startup_duration_seconds{\n    job=~\"$job\",\n    quantile=\"0.95\"\n  }\n)\n",
     "legendFormat": "P95"
    },
    {
     "expr": "max(\n  karpenter_pods_startup_duration_seconds{\n    job=~\"$job\",\n    quantile=\"0.99\"\n  }\n)\n",
     "legendFormat": "P99"
    }
   ]
  }
 ]
}