{
 "title": "Karpenter",
 "description": "Display all useful Karpenter metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nodepool",
    "query": {
     "query": "label_values(karpenter_nodepools_limit,nodepool)"
    }
   },
   {
    "name": "application",
    "query": {
     "query": "query_result(kube_deployment_created OR kube_statefulset_created)"
    }
   },
   {
    "name": "zone",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable,zone)"
    }
   },
   {
    "name": "arch",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable,arch)"
    }
   },
   {
    "name": "capacity_type",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable,capacity_type)"
    }
   },
   {
    "name": "instance_type",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable,instance_type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster CPU Requests",
   "type": "stat",
   "description": "Total number of cpu resources requested by all pods on the current Nodepool",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_nodes_total_pod_requests{resource_type=\"cpu\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Cluster Memory Requests",
   "type": "stat",
   "description": "Total number of memory resources requested by all pods on the current Nodepool",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_nodes_total_pod_requests{resource_type=\"memory\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Total number of Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_labels{label_karpenter_sh_nodepool!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spot Node Percentage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(karpenter_nodes_allocatable{capacity_type=\"spot\",zone=~\"$zone\"}) or vector(0)) / count(karpenter_nodes_allocatable{zone=~\"$zone\"})*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(karpenter_pods_state)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cluster CPU Allocation",
   "type": "stat",
   "description": "Percentage of resources requested by all pods from those available on the current Nodepool nodes",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_nodes_total_pod_requests{nodepool=~\"$nodepool\",resource_type=\"cpu\"}) / sum(karpenter_nodes_allocatable{nodepool=~\"$nodepool\", resource_type=\"cpu\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Cluster Memory Allocation",
   "type": "stat",
   "description": "Percentage of resources requested by all pods from those available on the current Nodepool nodes",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_nodes_total_pod_requests{nodepool=~\"$nodepool\",resource_type=\"memory\"}) / sum(karpenter_nodes_allocatable{nodepool=~\"$nodepool\", resource_type=\"memory\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Node  Distribution by AZ",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_labels{label_karpenter_sh_nodepool!=\"\"}) by (label_topology_kubernetes_io_zone)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod  Distribution by Aviability Zone",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_pods_state{}) by (zone)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pod  Distribution by Nodepool",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_pods_state{}) by (nodepool)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Node  Distribution by Nodepool",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (label_karpenter_sh_nodepool) (\n  kube_node_labels{label_karpenter_sh_nodepool!=\"\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Nodepool usage percentage of limit",
   "type": "timeseries",
   "description": "Percentage of how many resources Karpenter launched from the total Nodepool limit",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (nodepool, resource_type)(\n  karpenter_nodepools_usage{resource_type=~\"cpu|memory\"}\n)\n/\nsum by (nodepool, resource_type)(\n  karpenter_nodepools_limit{resource_type=~\"cpu|memory\"}\n) * 100",
     "legendFormat": "{{nodepool}}-{{resource_type}}"
    }
   ]
  },
  {
   "title": "Cluster CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(karpenter_nodes_total_pod_requests{resource_type=\"cpu\"}) + sum(karpenter_nodes_total_daemon_requests{resource_type=\"cpu\"})",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(karpenter_nodes_total_pod_requests{resource_type=\"cpu\"})",
     "legendFormat": "Requested"
    }
   ]
  },
  {
   "title": "Cluster Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(karpenter_nodes_allocatable{resource_type=\"memory\"})",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(karpenter_nodes_total_pod_requests{resource_type=\"memory\"})",
     "legendFormat": "Requested"
    }
   ]
  },
  {
   "title": "Total number of errors returned from CloudProvider calls.",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "karpenter_cloudprovider_errors_total{controller!~\"node.termination|nodeclaim.termination\", error!=\"NodeClaimNotFoundError\"}",
     "legendFormat": "{{controller}}-{{error}}"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Node Summary",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "((karpenter_nodes_total_daemon_requests{resource_type=\"cpu\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\"} or karpenter_nodes_allocatable*0) + \n(karpenter_nodes_total_pod_requests{resource_type=\"cpu\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\"} or karpenter_nodes_allocatable*0)) / \nkarpenter_nodes_allocatable{resource_type=\"cpu\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\"}",
     "legendFormat": "CPU Utilization"
    },
    {
     "expr": "((karpenter_nodes_total_daemon_requests{resource_type=\"memory\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\"} or karpenter_nodes_allocatable*0) + \n(karpenter_nodes_total_pod_requests{resource_type=\"memory\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\"} or karpenter_nodes_allocatable*0)) / \nkarpenter_nodes_allocatable{resource_type=\"memory\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\"}",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "karpenter_nodes_total_daemon_requests{resource_type=\"pods\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\"} + \nkarpenter_nodes_total_pod_requests{resource_type=\"pods\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\"}",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "label_replace(\n    sum by (node)(node_time_seconds) - sum by (node)(node_boot_time_seconds),\n    \"node_name\", \"$1\", \"node\", \"(.+)\"\n)",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Node Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "increase(karpenter_nodeclaims_created_total{}[5m])",
     "legendFormat": "created-\"{{nodepool}}\"-{{reason}}"
    },
    {
     "expr": "- increase(karpenter_nodeclaims_terminated_total{}[5m])",
     "legendFormat": "terminated-\"{{nodepool}}\"-{{reason}}"
    }
   ]
  },
  {
   "title": "Node AZ Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "count(karpenter_nodes_total_pod_requests{resource_type=\"pods\"}) by (zone)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node CPU Reservation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "karpenter_nodes_total_pod_requests{nodepool=~\"$nodepool\",resource_type=\"cpu\"} / karpenter_nodes_allocatable{nodepool=~\"$nodepool\",resource_type=\"cpu\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Node Memory Reservation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "karpenter_nodes_total_pod_requests{nodepool=~\"$nodepool\",resource_type=\"memory\"} / karpenter_nodes_allocatable{nodepool=~\"$nodepool\", resource_type=\"memory\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Interruption Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "idelta(karpenter_interruption_received_messages_total[1m])",
     "legendFormat": "{{message_type}}"
    }
   ]
  },
  {
   "title": "Deleted Interruption Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "sum(idelta(karpenter_interruption_deleted_messages_total[1m]))",
     "legendFormat": "Number of messages deleted"
    }
   ]
  },
  { "title": "Pods by Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Total Number of Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum(karpenter_pods_state{name=~\"$application.*\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pod  Distribution by Availability zone",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "sum(karpenter_pods_state{name=~\"$application.*\"}) by (zone)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pod Skew By  Availability zone",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "max(sum(karpenter_pods_state) by (zone)) - min(sum(karpenter_pods_state) by (zone))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Karpenter Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "app_kubernetes_io_instance: \"karpenter\""
    }
   ]
  }
 ]
}