{
 "title": "KubeCost",
 "description": "fixed images",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_labels, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Wide", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "AVG Cluster Cost (last 3 days) DAILY",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_total_hourly_cost * 24)"
    }
   ]
  },
  {
   "title": "Cluster Hour Price (last 12h)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expr": "sum(node_total_hourly_cost)", "legendFormat": "Cluster Hour Cost" }
   ]
  },
  {
   "title": "Estimative Cluster Cost (last 30 days based)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(node_total_hourly_cost * 720)"
    }
   ]
  },
  {
   "title": "Relative price now vs (7/1)d ago (Hour Price)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (\n  avg_over_time(\n    sum(node_total_hourly_cost) [1d:1h]\n  )\n/\n  avg_over_time(\n    sum(node_total_hourly_cost) [7d:1h]\n  )\n)",
     "legendFormat": "Relative price now vs 7d ago (Hour Price)"
    },
    {
     "expr": "1 - (\n  avg(sum(node_total_hourly_cost))\n/\n  avg_over_time(\n    sum(node_total_hourly_cost) [1d:1h]\n  )\n)",
     "legendFormat": "Relative price now vs 1d ago (Hour Price)"
    }
   ]
  },
  {
   "title": "Standard Variation of Cost by InstanceType (7d/1d)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "stdvar_over_time( sum(node_total_hourly_cost) by (instance_type) [7d:1d] ) > 0",
     "legendFormat": "{{ instance_type }}"
    }
   ]
  },
  {
   "title": "Estimated Top 20 by Container (30 days)",
   "type": "table",
   "gridPos": { "h": 23, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(\n  20,\n  sum(\n    sum(container_memory_allocation_bytes) by (container, instance)\n      * on(instance) group_left()\n      ( max by (instance) (node_ram_hourly_cost) / 1024 / 1024 / 1024 * 730 )\n  +\n    sum(container_cpu_allocation) by (container, instance)\n      * on(instance) group_left()\n      ( max by (instance) (node_cpu_hourly_cost) * 730 )\n  ) by (container)\n)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Hour Cost",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  sum(container_memory_allocation_bytes) by (namespace, instance)\n    * on(instance) group_left()\n    ( max by (instance) (node_ram_hourly_cost) / 1024 / 1024 / 1024 )\n+\n  sum(container_cpu_allocation) by (namespace, instance)\n    * on(instance) group_left()\n    ( max by (instance) (node_cpu_hourly_cost) )\n) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Hour Price by Container",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  sum(container_memory_allocation_bytes) by (namespace, instance)\n    * on(instance) group_left()\n    ( max by (instance) (node_ram_hourly_cost) / 1024 / 1024 / 1024 )\n+\n  sum(container_cpu_allocation) by (namespace, instance)\n    * on(instance) group_left()\n    ( max by (instance) (node_cpu_hourly_cost) )\n) by (namespace)",
     "legendFormat": "{{namespace}} / {{container}}"
    }
   ]
  },
  { "title": "PVCs (AWS EBS)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Kubernetes EBS alocation price by day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(sum(pv_hourly_cost) by (persistentvolume) * 24 * 100)",
     "legendFormat": "{{persistentvolume}}"
    }
   ]
  },
  { "title": "KubeCost Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Running Pods",
   "type": "stat",
   "description": "number of running pods",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\", namespace=\"kubecost\", pod=~\".*kubecost.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OOM Kills (24h)",
   "type": "timeseries",
   "description": "restart increments over 24h",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "increase(container_oom_events_total{namespace=\"kubecost\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage (cores) per pod/container",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by (container) (rate(container_cpu_usage_seconds_total{namespace=\"kubecost\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "description": "CPU usage percentage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "100 *\nsum by (namespace, pod, container) (\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"kubecost\",\n    pod=~\"kubecost.*\",\n    container!=\"\"\n  }[5m])\n)\n/\nclamp_min(\n  sum by (namespace, pod, container) (\n    kube_pod_container_resource_requests{\n      namespace=\"kubecost\",\n      pod=~\"kubecost.*\",\n      container!=\"\",\n      resource=\"cpu\"\n    }\n  ),\n  0.001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\", namespace=\"kubecost\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "timeseries",
   "description": "Memory usage percentage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "100 *\nsum by (namespace, pod) (\n  container_memory_working_set_bytes{\n    namespace=\"kubecost\",\n    pod=~\"kubecost.*\",\n    container!=\"\", container!=\"POD\"\n  }\n)\n/\nclamp_min(\n  sum by (namespace, pod) (\n    kube_pod_container_resource_limits{\n      namespace=\"kubecost\",\n      pod=~\"kubecost.*\",\n      resource=\"memory\"\n    }\n  ),\n  1\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container restarts (24h)",
   "type": "timeseries",
   "description": "restart increments over 24h",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"kubecost\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}