{
 "title": "TFY Proxy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,10m,15m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests in flight",
   "type": "stat",
   "description": "The number of requests currently being handled by the server.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(caddy_http_requests_in_flight{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "stat",
   "description": "Total requests handled in the selected time range.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_requests_total{}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "stat",
   "description": "Rate of requests handled per second in the selected time range.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(caddy_http_requests_total{}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Median request duration",
   "type": "stat",
   "description": "Median round-trip request duration for the selected time range.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(caddy_http_request_duration_seconds_bucket{}[$__range])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Median response duration",
   "type": "stat",
   "description": "Median time-to-first-byte response duration for the selected time range.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(caddy_http_response_duration_seconds_bucket{}[$__range])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total middleware errors",
   "type": "stat",
   "description": "A number of middleware errors encountered while handling requests in the selected time range.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_request_errors_total{}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Median request size",
   "type": "stat",
   "description": "Median request (estimated) size in bytes in the selected time range. Includes body.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(caddy_http_request_size_bytes_bucket{}[$__range])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Median response size",
   "type": "stat",
   "description": "Median returned response body size in bytes in the selected time range.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(caddy_http_response_size_bytes_bucket{}[$__range])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests size",
   "type": "stat",
   "description": "Sum of the sizes of all received requests in the selected time range.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_request_size_bytes_sum{}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total responses size",
   "type": "stat",
   "description": "Sum of sizes of all response bodies in the selected time range.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_response_size_bytes_sum{}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx response percentage",
   "type": "stat",
   "description": "Percentage of responses with 4xx status code in all responses.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_response_duration_seconds_count{code=~\"4..\"}[$__range])) / sum(increase(caddy_http_response_duration_seconds_count{}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx response percentage",
   "type": "stat",
   "description": "Percentage of responses with 4xx status code in all responses.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_response_duration_seconds_count{code=~\"5..\"}[$__range])) / sum(increase(caddy_http_response_duration_seconds_count{}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate of requests by HTTP method (stacked)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum(rate(caddy_http_request_duration_seconds_count{}[$interval])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP status breakdown",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(caddy_http_request_duration_seconds_count{}[$__range])) by (code)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP method breakdown",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(caddy_http_request_duration_seconds_count{}[$__range])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request duration percentiles",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(caddy_http_request_duration_seconds_bucket{}[$interval])) by (le))",
       "legendFormat": "0.99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(caddy_http_request_duration_seconds_bucket{}[$interval])) by (le))",
       "legendFormat": "0.95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(caddy_http_request_duration_seconds_bucket{}[$interval])) by (le))",
       "legendFormat": "0.90"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(caddy_http_request_duration_seconds_bucket{}[$interval])) by (le))",
       "legendFormat": "0.75"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(caddy_http_request_duration_seconds_bucket{}[$interval])) by (le))",
       "legendFormat": "0.5"
      }
     ]
    },
    {
     "title": "Data transfer rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(caddy_http_request_size_bytes_sum{}[$interval]))",
       "legendFormat": "request"
      },
      {
       "expr": "-sum(rate(caddy_http_response_size_bytes_sum{}[$interval]))",
       "legendFormat": "response"
      }
     ]
    },
    {
     "title": "Rate of 4xx and 5xx responses",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "sum(rate(caddy_http_request_duration_seconds_count{code=~\"4..|5..\"}[$interval])) by (code)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Middleware error rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "rate(caddy_http_request_errors_total{}[$interval])",
       "legendFormat": "errors"
      }
     ]
    }
   ]
  },
  {
   "title": "Heatmaps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request duration heatmap",
     "type": "heatmap",
     "description": "Round-trip request duration heatmap.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum(increase(caddy_http_request_duration_seconds_bucket{}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request size heatmap",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "sum(increase(caddy_http_request_size_bytes_bucket{}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response duration heatmap",
     "type": "heatmap",
     "description": "Response time-to-first-byte heatmap.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum(increase(caddy_http_response_duration_seconds_bucket{}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response size heatmap",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "sum(increase(caddy_http_response_size_bytes_bucket{}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  { "title": "tfy-proxy resource utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Running Pods",
   "type": "stat",
   "description": "number of running pods",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\", namespace=\"truefoundry\", pod=~\".*tfy-proxy.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OOM Kills (24h)",
   "type": "timeseries",
   "description": "restart increments over 24h",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "increase(container_oom_events_total{namespace=\"truefoundry\", pod=~\".*tfy-proxy.*\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage (cores) per pod/container",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (container) (rate(container_cpu_usage_seconds_total{namespace=\"truefoundry\", pod=~\".*tfy-proxy.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "description": "CPU usage percentage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "100 *\nsum by (namespace, pod, container) (\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"truefoundry\",\n    pod=~\".*tfy-proxy.*\",\n    container!=\"\"\n  }[5m])\n)\n/\nclamp_min(\n  sum by (namespace, pod, container) (\n    kube_pod_container_resource_requests{\n      namespace=\"truefoundry\",\n      pod=~\".*tfy-proxy.*\",\n      container!=\"\",\n      resource=\"cpu\"\n    }\n  ),\n  0.001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\", namespace=\"truefoundry\", pod=~\".*tfy-proxy.*\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "timeseries",
   "description": "Memory usage percentage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "100 *\nsum by (namespace, pod) (\n  container_memory_working_set_bytes{\n    namespace=\"truefoundry\",\n    pod=~\".*tfy-proxy.*\",\n    container!=\"\", container!=\"POD\"\n  }\n)\n/\nclamp_min(\n  sum by (namespace, pod) (\n    kube_pod_container_resource_limits{\n      namespace=\"truefoundry\",\n      pod=~\".*tfy-proxy.*\",\n      resource=\"memory\"\n    }\n  ),\n  1\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "app_kubernetes_io_instance: \"tfy-proxy-ingress\""
      }
     ]
    }
   ]
  }
 ]
}