{{- if and .Values.tunnel.token (not .Values.tunnel.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tfy-cloudflared.tunnelSecretName" . }}
  labels:
    {{- include "tfy-cloudflared.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "tfy-cloudflared.tunnelSecretKey" . }}: {{ .Values.tunnel.token | quote }}
{{- end }}
