{{- if .Values.caddy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tfy-cloudflared.caddyFullname" . }}-config
  labels:
    {{- include "tfy-cloudflared.caddyCommonLabels" . | nindent 4 }}
  annotations:
    {{- include "tfy-cloudflared.commonAnnotations" . | nindent 4 }}
data:
  Caddyfile: |
    {
    	admin 0.0.0.0:2019

    	log {
    		output stdout
    		format json
    		level INFO
    	}
    }

    :80 {
    	encode zstd gzip

    	log {
    		output stdout
    		format json
    	}

    	respond /healthz 200

    	@direct_url_http path_regexp direct_url_http ^/[^/]+/http:/{1,2}([^/]+):([0-9]+)(?:/(.*))?$
    	handle @direct_url_http {
    		rewrite * /{re.direct_url_http.3}

    		reverse_proxy {re.direct_url_http.1}:{re.direct_url_http.2} {
    			header_up X-Forwarded-Host {host}
    			header_up X-Original-URI {uri}

    			lb_try_duration 5s
    			lb_try_interval 250ms
    			fail_duration 10s
    			max_fails 2

    			transport http {
    				dial_timeout 3s
    				response_header_timeout 30s
    				read_timeout 5m
    				write_timeout 5m
    			}
    		}
    	}

    	@direct_url_https path_regexp direct_url_https ^/[^/]+/https:/{1,2}([^/]+):([0-9]+)(?:/(.*))?$
    	handle @direct_url_https {
    		rewrite * /{re.direct_url_https.3}

    		reverse_proxy {re.direct_url_https.1}:{re.direct_url_https.2} {
    			header_up X-Forwarded-Host {host}
    			header_up X-Original-URI {uri}

    			lb_try_duration 5s
    			lb_try_interval 250ms
    			fail_duration 10s
    			max_fails 2

    			transport http {
    				tls
    				tls_server_name {re.direct_url_https.1}
    				dial_timeout 3s
    				response_header_timeout 30s
    				read_timeout 5m
    				write_timeout 5m
    			}
    		}
    	}

    	@direct_https path_regexp direct_https ^/[^/]+/https/([^/]+):([0-9]+)(?:/(.*))?$
    	handle @direct_https {
    		rewrite * /{re.direct_https.3}

    		reverse_proxy {re.direct_https.1}:{re.direct_https.2} {
    			header_up X-Forwarded-Host {host}
    			header_up X-Original-URI {uri}

    			lb_try_duration 5s
    			lb_try_interval 250ms
    			fail_duration 10s
    			max_fails 2

    			transport http {
    				tls
    				tls_server_name {re.direct_https.1}
    				dial_timeout 3s
    				response_header_timeout 30s
    				read_timeout 5m
    				write_timeout 5m
    			}
    		}
    	}

    	@direct_http path_regexp direct_http ^/[^/]+/([^/]+):([0-9]+)(?:/(.*))?$
    	handle @direct_http {
    		rewrite * /{re.direct_http.3}

    		reverse_proxy {re.direct_http.1}:{re.direct_http.2} {
    			header_up X-Forwarded-Host {host}
    			header_up X-Original-URI {uri}

    			lb_try_duration 5s
    			lb_try_interval 250ms
    			fail_duration 10s
    			max_fails 2

    			transport http {
    				dial_timeout 3s
    				response_header_timeout 30s
    				read_timeout 5m
    				write_timeout 5m
    			}
    		}
    	}

    	respond 404
    }
{{- end }}
