{{- if and .Values.caddy.enabled .Values.caddy.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tfy-cloudflared.caddyServiceAccountName" . }}
  labels:
    {{- include "tfy-cloudflared.caddyServiceAccountLabels" . | nindent 4 }}
  annotations:
    {{- include "tfy-cloudflared.caddyServiceAccountAnnotations" . | nindent 4 }}
{{- end }}
