{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tfy-sandbox-server.fullname" . }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "tfy-sandbox-server.commonLabels" . | nindent 4 }}
  annotations:
    {{- include "tfy-sandbox-server.commonAnnotations" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
