apiVersion: v1
kind: Service
metadata:
  name: {{ include "tfy-sandbox-server.fullname" . }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "tfy-sandbox-server.serviceLabels" . | nindent 4 }}
  annotations:
    {{- include "tfy-sandbox-server.serviceAnnotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "tfy-sandbox-server.selectorLabels" . | nindent 4 }}
