{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tfy-sandbox-server.serviceAccountName" . }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "tfy-sandbox-server.serviceAccountLabels" . | nindent 4 }}
  annotations:
    {{- include "tfy-sandbox-server.serviceAccountAnnotations" . | nindent 4 }}
{{- end }}
