apiVersion: v2
name: truefoundry-monitoring
description: Monitoring stack for TrueFoundry control plane - Prometheus, Logs, and Grafana
version: 0.1.7
maintainers:
  - name: truefoundry
dependencies:
  - name: prometheus
    version: 29.12.0
    repository: https://prometheus-community.github.io/helm-charts
    alias: prometheus
    condition: prometheus.enabled
  - name: tfy-logs
    version: 0.1.20
    repository: https://truefoundry.github.io/infra-charts/
    alias: logs
    condition: logs.enabled
  - name: grafana
    version: 10.4.0
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: headlamp
    version: "0.41.0"
    repository: "https://kubernetes-sigs.github.io/headlamp/"
    condition: headlamp.enabled
