{{- if .Values.tfyProxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tfy-proxy.fullname" . }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "tfy-proxy.serviceLabels" . | nindent 4 }}
  annotations:
    {{- include "tfy-proxy.serviceAnnotations" . | nindent 4 }}
spec:
  type: {{ .Values.tfyProxy.service.type }}
  ports:
    - name: http
      port: {{ .Values.tfyProxy.service.port }}
      targetPort: {{ .Values.tfyProxy.service.port }}
      protocol: TCP
      appProtocol: tcp
    {{- if .Values.tfyProxy.adminApi.enabled }}
    - name: metrics
      port: 2019
      targetPort: metrics
    {{- end }}
  selector:
    {{- include "truefoundry.selectorLabels" (dict "context" . "name" "tfy-proxy") | nindent 4 }}
{{- end }}
