{{- if .Values.headlamp.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-headlamp-readonly
  namespace: {{ include "truefoundry-monitoring.controlPlaneNamespace" . }}
  labels:
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-headlamp-readonly
subjects:
  - kind: ServiceAccount
    name: {{ include "truefoundry-monitoring.headlamp.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
