{{- if .Values.headlamp.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-headlamp-readonly
  labels:
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  {{- if .Values.headlamp.allowPodExec }}
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  {{- end }}
{{- end }}
