{{- if .Values.headlamp.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: headlamp-kubeconfig
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        server: https://kubernetes.default.svc
      name: in-cluster
    contexts:
    - context:
        cluster: in-cluster
        user: headlamp-sa
        namespace: {{ include "truefoundry-monitoring.controlPlaneNamespace" . }}
      name: in-cluster
    current-context: in-cluster
    users:
    - name: headlamp-sa
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
{{- end }}
