{{- if .Values.tfyGateway }}
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Values.tfyGateway.name | default "tfy-wildcard" }}
  namespace: istio-system
  labels:
    {{- include "tfy-istio-ingress.labels" . | nindent 4 }}
  annotations:
    {{- include "tfy-istio-ingress.annotations" . | nindent 4 }}
spec:
  selector:
    {{- tpl (toYaml .Values.tfyGateway.spec.selector) . | nindent 4 }}
  servers:
  {{- range .Values.tfyGateway.spec.servers }}
  {{- $hasWildcard := false }}
  {{- range .hosts }}
  {{- if eq . "*" }}
  {{- $hasWildcard = true }}
  {{- end }}
  {{- end }}
  - hosts:
    {{- if $hasWildcard }}
    - "*"
    {{- else }}
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
    {{- end }}
    {{- toYaml (omit . "hosts") | nindent 4 }}
  {{- end }}
{{- end }}
