{{- if and .Values.tfyBuild.enabled .Values.tfyBuildkitdService.enabled .Values.tfyBuildkitdService.serviceAccount.create .Values.tfyBuildkitdService.serviceAccount.name -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tfy-buildkitd-service.serviceAccountName" . }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "tfy-buildkitd-service.serviceAccountLabels" . | nindent 4 }}
  annotations:
    {{- include "tfy-buildkitd-service.serviceAccountAnnotations" . | nindent 4 }}
{{- if hasKey .Values.tfyBuildkitdService.serviceAccount "automountServiceAccountToken" }}
automountServiceAccountToken: {{ .Values.tfyBuildkitdService.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- end }}
