{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tfy-cloudflared.serviceAccountName" . }}
  labels:
    {{- include "tfy-cloudflared.serviceAccountLabels" . | nindent 4 }}
  annotations:
    {{- include "tfy-cloudflared.serviceAccountAnnotations" . | nindent 4 }}
{{- end }}
