{{- if .Values.addCaCertificateVolume.enabled -}}
apiVersion: policies.kyverno.io/v1
kind: GeneratingPolicy
metadata:
  name: {{ include "tfy-kyverno.fullname" . }}-clone-ca-cert-configmap
spec:
  evaluation:
    synchronize:
      enabled: true
  matchConstraints:
    {{- if .Values.addCaCertificateVolume.excludeNamespaces }}
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            {{- range .Values.addCaCertificateVolume.excludeNamespaces }}
            - {{ . }}
            {{- end }}
    {{- end }}
    resourceRules:
      - apiGroups: ['']
        apiVersions: ['v1']
        operations: ['CREATE']
        resources: ['namespaces']
  variables:
    - name: nsName
      expression: "object.metadata.name"
    - name: source
      expression: >-
        resource.Get("v1", "configmaps", "{{ .Values.addCaCertificateVolume.sourceNamespace }}", "{{ .Values.addCaCertificateVolume.sourceConfigMap.name }}")
  generate:
    - expression: "generator.Apply(variables.nsName, [variables.source])"
{{- end -}}
