{{- if and .Values.syncSecrets.enabled .Values.syncSecrets.items -}}
apiVersion: policies.kyverno.io/v1
kind: GeneratingPolicy
metadata:
  name: {{ include "tfy-kyverno.fullname" . }}-sync-secrets
spec:
  evaluation:
    synchronize:
      enabled: true
  matchConstraints:
    {{- if or .Values.syncSecrets.excludeNamespaces .Values.syncSecrets.includeNamespaces }}
    namespaceSelector:
      matchExpressions:
        {{- if .Values.syncSecrets.excludeNamespaces }}
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            {{- range .Values.syncSecrets.excludeNamespaces }}
            - {{ . }}
            {{- end }}
        {{- end }}
        {{- if .Values.syncSecrets.includeNamespaces }}
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            {{- range .Values.syncSecrets.includeNamespaces }}
            - {{ . }}
            {{- end }}
        {{- end }}
    {{- end }}
    resourceRules:
      - apiGroups: ['']
        apiVersions: ['v1']
        operations: ['CREATE']
        resources: ['namespaces']
  variables:
    - name: nsName
      expression: "object.metadata.name"
    {{- range $i, $secret := .Values.syncSecrets.items }}
    - name: source{{ $i }}
      expression: >-
        resource.Get("v1", "secrets", "{{ $secret.namespace }}", "{{ $secret.name }}")
    {{- end }}
  generate:
    - expression: >-
        generator.Apply(variables.nsName, [
        {{- range $i, $secret := .Values.syncSecrets.items }}
        {{- if $i }}, {{ end }}variables.source{{ $i }}
        {{- end }}
        ])
{{- end -}}
