{{- if .Values.stdioMcpProxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stdio-mcp-proxy.fullname" . }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "stdio-mcp-proxy.deploymentLabels" . | nindent 4 }}
  annotations:
    {{- include "stdio-mcp-proxy.deploymentAnnotations" . | nindent 4 }}
spec:
  replicas: {{- include "stdio-mcp-proxy.replicas" . | indent 1 }}
  selector:
    matchLabels:
      {{- include "truefoundry.selectorLabels" (dict "context" . "name" "stdio-mcp-proxy") | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "stdio-mcp-proxy.podAnnotations" . | nindent 8 }}
      labels:
        {{- include "stdio-mcp-proxy.podLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "stdio-mcp-proxy.serviceAccountName" . }}
      {{- with .Values.stdioMcpProxy.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if and .Values.global.customCA.enabled (eq (include "truefoundry.customCA.useDirectMount" .) "false") }}
      initContainers:
        {{- include "truefoundry.customCA.initContainer" . | nindent 8 }}
      {{- end }}
      containers:
        - name: "stdio-mcp-proxy"
          {{- with .Values.stdioMcpProxy.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- include "stdio-mcp-proxy.env" . | trim | nindent 12 }}
          image: "{{ .Values.stdioMcpProxy.image.registry | default .Values.global.image.registry }}/{{ .Values.stdioMcpProxy.image.repository }}:{{ .Values.stdioMcpProxy.image.tag }}"
          imagePullPolicy: {{ .Values.stdioMcpProxy.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.stdioMcpProxy.service.port }}
              protocol: TCP
          resources:
            {{- include "stdio-mcp-proxy.resources" . | indent 12 }}
          livenessProbe:
            failureThreshold: {{ .Values.stdioMcpProxy.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.stdioMcpProxy.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.stdioMcpProxy.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.stdioMcpProxy.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.stdioMcpProxy.livenessProbe.timeoutSeconds }}
            httpGet:
              path: /healthz
              port: {{ .Values.stdioMcpProxy.service.port }}
          readinessProbe:
            failureThreshold: {{ .Values.stdioMcpProxy.readinessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.stdioMcpProxy.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.stdioMcpProxy.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.stdioMcpProxy.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.stdioMcpProxy.readinessProbe.timeoutSeconds }}
            httpGet:
              path: /healthz
              port: {{ .Values.stdioMcpProxy.service.port }}
          volumeMounts:
            {{- include "stdio-mcp-proxy.volumeMounts" . | nindent 12 }}
      imagePullSecrets:
        {{- include "stdio-mcp-proxy.imagePullSecrets" . | nindent 8 }}
      volumes:
        {{- include "stdio-mcp-proxy.volumes" . | nindent 8 }}
      {{- $mergedNodeSelector := mergeOverwrite (deepCopy .Values.global.nodeSelector) (deepCopy .Values.stdioMcpProxy.nodeSelector) }}
      {{- if $mergedNodeSelector }}
      nodeSelector:
        {{- toYaml $mergedNodeSelector | nindent 8 }}
      {{- end }}
      {{- $mergedAffinity := dict | merge .Values.stdioMcpProxy.affinity .Values.global.affinity }}
      {{- if $mergedAffinity }}
      affinity:
      {{- toYaml $mergedAffinity | nindent 8 }}
      {{- end }}
      topologySpreadConstraints:
        {{- if .Values.stdioMcpProxy.topologySpreadConstraints }}
        {{- toYaml .Values.stdioMcpProxy.topologySpreadConstraints | nindent 8 }}
        {{- else }}
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              {{- include "truefoundry.selectorLabels" (dict "context" . "name" "stdio-mcp-proxy") | nindent 14 }}
        {{- end }}
      tolerations:
        {{- .Values.global.tolerations | toYaml | nindent 8 }}
        {{- if .Values.stdioMcpProxy.tolerations }}
        {{- .Values.stdioMcpProxy.tolerations | toYaml | nindent 8 }}
        {{- end }}
{{- end }}
