{{- if and .Values.stdioMcpProxy.enabled .Values.stdioMcpProxy.serviceAccount.create .Values.stdioMcpProxy.serviceAccount.name }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stdio-mcp-proxy.serviceAccountName" . }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "stdio-mcp-proxy.serviceAccountLabels" . | nindent 4 }}
  annotations:
    {{- include "stdio-mcp-proxy.serviceAccountAnnotations" . | nindent 4 }}
{{- if hasKey .Values.stdioMcpProxy.serviceAccount "automountServiceAccountToken" }}
automountServiceAccountToken: {{ .Values.stdioMcpProxy.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- end }}
