{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "tfy-sandbox-server.fullname" . }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "tfy-sandbox-server.pdbLabels" . | nindent 4 }}
  annotations:
    {{- include "tfy-sandbox-server.pdbAnnotations" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "tfy-sandbox-server.selectorLabels" . | nindent 6 }}
{{- end }}
