name: PR Checks

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  validate-pr-title:
    uses: truefoundry/workflows/.github/workflows/pr-title-check.yml@main
